/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_STUB_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/toscore/cmsservice/ConfigurationManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <unordered_set>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service ConfigurationManager. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class ConfigurationManagerStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual ConfigurationManager {
 public:
    /**
    * Sends a broadcast event for ChangeDataNotify. Should not be called directly.
    * Instead, the "fire<broadcastName>Event" methods of the stub should be used.
    */
    virtual void fireChangeDataNotifyEvent(const std::string &_tableName) = 0;


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for ConfigurationManager.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ConfigurationManagerStubRemoteEvent
{
public:
    virtual ~ConfigurationManagerStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service ConfigurationManager to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ConfigurationManagerStub
    : public virtual CommonAPI::Stub<ConfigurationManagerStubAdapter, ConfigurationManagerStubRemoteEvent>
{
public:
    typedef std::function<void (ConfigurationManager::CreateDBStatus _output)> createDefaultKVDBReply_t;
    typedef std::function<void (ConfigurationManager::ModifyStatus _value)> modifyKVDBReply_t;
    typedef std::function<void (ConfigurationManager::ReadKVDBData _statusValue)> readKVDBReply_t;
    typedef std::function<void (ConfigurationManager::DeleteStatus _value)> deleteKVDBReply_t;
    typedef std::function<void (std::string _response)> getConfigVersionReply_t;
    typedef std::function<void (ConfigurationManager::UpdateDBStatus _updateValue)> updateConfigRequestReply_t;
    typedef std::function<void (ConfigurationManager::setCotaStateStatus _value)> setCOTACompletionStatusReply_t;
    typedef std::function<void (ConfigurationManager::RestoreDefaultStatus _value)> restoreDefaultKVDBReply_t;
    typedef std::function<void (ConfigurationManager::RestoreFactoryStatus _sValue)> restoreFactoryKVDBReply_t;
    typedef std::function<void (ConfigurationManager::IsFactoryStatus _fValue)> isFactoryModeKVDataReply_t;
    typedef std::function<void (ConfigurationManager::DefaultDBStatus _sValue)> isDefaultKVDBAvlbleReply_t;
    typedef std::function<void (ConfigurationManager::FactoryDBStatus _sValue)> isFactoryKVDBAvlbleReply_t;
    typedef std::function<void (ConfigurationManager::ReadKVDBData _status)> readConfigTableReply_t;
    typedef std::function<void (std::string _compVersion)> getVersionReply_t;
    typedef std::function<void (uint8_t _componentID)> getComponentIDReply_t;

    virtual ~ConfigurationManagerStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 16);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * brief : Interface to create Default database
     * param[in] : input : Structure containing the database details needed to create a new table
     * param[out] : output : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method createDefaultKVDB.
    virtual void createDefaultKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::CreateDefaultKVDBInfo _input, createDefaultKVDBReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to write/update database
     * param[in] : input : Structure containing the database details needed to modify the data
     * param[out] : value : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method modifyKVDB.
    virtual void modifyKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::ModifyKVDBInfo _input, modifyKVDBReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to read data from database
     * param[in] : getValue : Structure containing the database details needed to read the data
     * param[out] : statusValue : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method readKVDB.
    virtual void readKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::ReadKVDBInfo _getValue, readKVDBReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to delete data from database
     * param[in] : deletValue : Structure containing the database details needed to delete the data
     * param[out] : value : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method deleteKVDB.
    virtual void deleteKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::DeleteKVDBInfo _deletValue, deleteKVDBReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to get the version of the table
     * param[in] : tableName : Name of the table
     * param[in] :typevalue  :  cota type for keystore/configstore
     * param[out] : response : Version of the table
     */
    /// This is the method that will be called on remote calls on the method getConfigVersion.
    virtual void getConfigVersion(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, ConfigurationManager::CotaType _typevalue, getConfigVersionReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to update configuration over COTA
     * param[in] : filePath : The path of the file which is used to update the configuration
     * param[out] : updateValue : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method updateConfigRequest.
    virtual void updateConfigRequest(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _filePath, ConfigurationManager::CotaType _typevalue, updateConfigRequestReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to update the COTA completion status
     * param[in] : typevalue : Enumeration that specifies the type of configuration change
     * param[out] : value : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method setCOTACompletionStatus.
    virtual void setCOTACompletionStatus(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::CotaType _typevalue, setCOTACompletionStatusReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to restore into Default database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method restoreDefaultKVDB.
    virtual void restoreDefaultKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, restoreDefaultKVDBReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to restore into Factory database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method restoreFactoryKVDB.
    virtual void restoreFactoryKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, restoreFactoryKVDBReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to check database is of Factory mode
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : fValue : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method isFactoryModeKVData.
    virtual void isFactoryModeKVData(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, isFactoryModeKVDataReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to check Default database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method isDefaultKVDBAvlble.
    virtual void isDefaultKVDBAvlble(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, isDefaultKVDBAvlbleReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to check Factory database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method isFactoryKVDBAvlble.
    virtual void isFactoryKVDBAvlble(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, isFactoryKVDBAvlbleReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to read whole configuration from table
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : status : Enumeration containing the status of the response
     */
    /// This is the method that will be called on remote calls on the method readConfigTable.
    virtual void readConfigTable(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, readConfigTableReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    /// This is the method that will be called on remote calls on the method getVersion.
    virtual void getVersion(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getVersionReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : componentID : Component identification number
     */
    /// This is the method that will be called on remote calls on the method getComponentID.
    virtual void getComponentID(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getComponentIDReply_t _reply) = 0;
    /*
     * description: 
     * brief : Event to get update in latest table of a database
     * param[out] : tableName : Name of the table corresponding to a module
     */
    /// Sends a broadcast event for ChangeDataNotify.
    virtual void fireChangeDataNotifyEvent(const std::string &_tableName) {
        auto stubAdapter = CommonAPI::Stub<ConfigurationManagerStubAdapter, ConfigurationManagerStubRemoteEvent>::stubAdapter_.lock();
        if (stubAdapter)
            stubAdapter->fireChangeDataNotifyEvent(_tableName);
    }


    using CommonAPI::Stub<ConfigurationManagerStubAdapter, ConfigurationManagerStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<ConfigurationManagerStubAdapter, ConfigurationManagerStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<ConfigurationManagerStubAdapter, ConfigurationManagerStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef ConfigurationManagerStubRemoteEvent RemoteEventType;
    typedef ConfigurationManager StubInterface;
};

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_STUB_HPP_
