/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_SOMEIP_PROXY_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_SOMEIP_PROXY_HPP_

#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerProxyBase.hpp>
#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Proxy.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Event.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <string>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

class ConfigurationManagerSomeIPProxy
    : virtual public ConfigurationManagerProxyBase,
      virtual public CommonAPI::SomeIP::Proxy {
public:
    ConfigurationManagerSomeIPProxy(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection);

    virtual ~ConfigurationManagerSomeIPProxy();

    virtual ChangeDataNotifyEvent& getChangeDataNotifyEvent();

    /*
     * description: 
     * brief : Interface to create Default database
     * param[in] : input : Structure containing the database details needed to create a new table
     * param[out] : output : Enumeration containing the status of the response
     */
    virtual void createDefaultKVDB(ConfigurationManager::CreateDefaultKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::CreateDBStatus &_output, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> createDefaultKVDBAsync(const ConfigurationManager::CreateDefaultKVDBInfo &_input, CreateDefaultKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to write/update database
     * param[in] : input : Structure containing the database details needed to modify the data
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void modifyKVDB(ConfigurationManager::ModifyKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ModifyStatus &_value, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> modifyKVDBAsync(const ConfigurationManager::ModifyKVDBInfo &_input, ModifyKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to read data from database
     * param[in] : getValue : Structure containing the database details needed to read the data
     * param[out] : statusValue : Enumeration containing the status of the response
     */
    virtual void readKVDB(ConfigurationManager::ReadKVDBInfo _getValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_statusValue, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> readKVDBAsync(const ConfigurationManager::ReadKVDBInfo &_getValue, ReadKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to delete data from database
     * param[in] : deletValue : Structure containing the database details needed to delete the data
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void deleteKVDB(ConfigurationManager::DeleteKVDBInfo _deletValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DeleteStatus &_value, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> deleteKVDBAsync(const ConfigurationManager::DeleteKVDBInfo &_deletValue, DeleteKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to get the version of the table
     * param[in] : tableName : Name of the table
     * param[in] :typevalue  :  cota type for keystore/configstore
     * param[out] : response : Version of the table
     */
    virtual void getConfigVersion(std::string _tableName, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, std::string &_response, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> getConfigVersionAsync(const std::string &_tableName, const ConfigurationManager::CotaType &_typevalue, GetConfigVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to update configuration over COTA
     * param[in] : filePath : The path of the file which is used to update the configuration
     * param[out] : updateValue : Enumeration containing the status of the response
     */
    virtual void updateConfigRequest(std::string _filePath, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::UpdateDBStatus &_updateValue, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> updateConfigRequestAsync(const std::string &_filePath, const ConfigurationManager::CotaType &_typevalue, UpdateConfigRequestAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to update the COTA completion status
     * param[in] : typevalue : Enumeration that specifies the type of configuration change
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void setCOTACompletionStatus(ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::setCotaStateStatus &_value, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> setCOTACompletionStatusAsync(const ConfigurationManager::CotaType &_typevalue, SetCOTACompletionStatusAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to restore into Default database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void restoreDefaultKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreDefaultStatus &_value, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> restoreDefaultKVDBAsync(const std::string &_tableName, RestoreDefaultKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to restore into Factory database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void restoreFactoryKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreFactoryStatus &_sValue, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> restoreFactoryKVDBAsync(const std::string &_tableName, RestoreFactoryKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to check database is of Factory mode
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : fValue : Enumeration containing the status of the response
     */
    virtual void isFactoryModeKVData(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::IsFactoryStatus &_fValue, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> isFactoryModeKVDataAsync(const std::string &_tableName, IsFactoryModeKVDataAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to check Default database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    virtual void isDefaultKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DefaultDBStatus &_sValue, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> isDefaultKVDBAvlbleAsync(const std::string &_tableName, IsDefaultKVDBAvlbleAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to check Factory database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    virtual void isFactoryKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::FactoryDBStatus &_sValue, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> isFactoryKVDBAvlbleAsync(const std::string &_tableName, IsFactoryKVDBAvlbleAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to read whole configuration from table
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : status : Enumeration containing the status of the response
     */
    virtual void readConfigTable(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_status, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> readConfigTableAsync(const std::string &_tableName, ReadConfigTableAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    virtual void getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : componentID : Component identification number
     */
    virtual void getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info);

    virtual std::future<CommonAPI::CallStatus> getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback, const CommonAPI::CallInfo *_info);

    virtual void getOwnVersion(uint16_t &_major, uint16_t &_minor) const;

    virtual std::future<void> getCompletionFuture();

private:
    CommonAPI::SomeIP::Event<ChangeDataNotifyEvent, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment >> changeDataNotify_;

    std::promise<void> completed_;
};

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_SOMEIP_PROXY_HPP_
