/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createConfigurationManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< ConfigurationManagerSomeIPProxy>(_address, _connection);
}

void initializeConfigurationManagerSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.toscore.cmsservice.ConfigurationManager:v1_0:commonapi.toscore.cmsservice.ConfigurationManager",
        0xfa6, 0x7d6, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.toscore.cmsservice.ConfigurationManager:v1_0",
        &createConfigurationManagerSomeIPProxy);
}

INITIALIZER(registerConfigurationManagerSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeConfigurationManagerSomeIPProxy);
}

ConfigurationManagerSomeIPProxy::ConfigurationManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection),
          changeDataNotify_(*this, 0x88b9, CommonAPI::SomeIP::event_id_t(0x80e9), CommonAPI::SomeIP::event_type_e::ET_EVENT , CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE, false, std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
{
}

ConfigurationManagerSomeIPProxy::~ConfigurationManagerSomeIPProxy() {
    completed_.set_value();
}


ConfigurationManagerSomeIPProxy::ChangeDataNotifyEvent& ConfigurationManagerSomeIPProxy::getChangeDataNotifyEvent() {
    return changeDataNotify_;
}

/*
 * description: 
 * brief : Interface to create Default database
 * param[in] : input : Structure containing the database details needed to create a new table
 * param[out] : output : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::createDefaultKVDB(ConfigurationManager::CreateDefaultKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::CreateDBStatus &_output, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::CreateDefaultKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t> deploy_input(_input, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::CreateDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t> deploy_output(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::CreateDefaultKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::CreateDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2711),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_input,
        _internalCallStatus,
        deploy_output);
    _output = deploy_output.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::createDefaultKVDBAsync(const ConfigurationManager::CreateDefaultKVDBInfo &_input, CreateDefaultKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::CreateDefaultKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t> deploy_input(_input, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::CreateDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t> deploy_output(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::CreateDefaultKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::CreateDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2711),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_input,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::CreateDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t > _output) {
            if (_callback)
                _callback(_internalCallStatus, _output.getValue());
        },
        std::make_tuple(deploy_output));
}

/*
 * description: 
 * brief : Interface to write/update database
 * param[in] : input : Structure containing the database details needed to modify the data
 * param[out] : value : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::modifyKVDB(ConfigurationManager::ModifyKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ModifyStatus &_value, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::ModifyKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t> deploy_input(_input, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::ModifyStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ModifyKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ModifyStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2712),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_input,
        _internalCallStatus,
        deploy_value);
    _value = deploy_value.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::modifyKVDBAsync(const ConfigurationManager::ModifyKVDBInfo &_input, ModifyKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::ModifyKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t> deploy_input(_input, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::ModifyStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ModifyKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ModifyStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2712),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_input,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::ModifyStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t > _value) {
            if (_callback)
                _callback(_internalCallStatus, _value.getValue());
        },
        std::make_tuple(deploy_value));
}

/*
 * description: 
 * brief : Interface to read data from database
 * param[in] : getValue : Structure containing the database details needed to read the data
 * param[out] : statusValue : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::readKVDB(ConfigurationManager::ReadKVDBInfo _getValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_statusValue, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::ReadKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t> deploy_getValue(_getValue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::ReadKVDBData, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t> deploy_statusValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ReadKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ReadKVDBData,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2713),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_getValue,
        _internalCallStatus,
        deploy_statusValue);
    _statusValue = deploy_statusValue.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::readKVDBAsync(const ConfigurationManager::ReadKVDBInfo &_getValue, ReadKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::ReadKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t> deploy_getValue(_getValue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::ReadKVDBData, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t> deploy_statusValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ReadKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ReadKVDBData,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2713),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_getValue,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::ReadKVDBData, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t > _statusValue) {
            if (_callback)
                _callback(_internalCallStatus, _statusValue.getValue());
        },
        std::make_tuple(deploy_statusValue));
}

/*
 * description: 
 * brief : Interface to delete data from database
 * param[in] : deletValue : Structure containing the database details needed to delete the data
 * param[out] : value : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::deleteKVDB(ConfigurationManager::DeleteKVDBInfo _deletValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DeleteStatus &_value, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::DeleteKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t> deploy_deletValue(_deletValue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::DeleteStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::DeleteKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::DeleteStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2714),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_deletValue,
        _internalCallStatus,
        deploy_value);
    _value = deploy_value.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::deleteKVDBAsync(const ConfigurationManager::DeleteKVDBInfo &_deletValue, DeleteKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::DeleteKVDBInfo, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t> deploy_deletValue(_deletValue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::DeleteStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::DeleteKVDBInfo,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::DeleteStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2714),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_deletValue,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::DeleteStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t > _value) {
            if (_callback)
                _callback(_internalCallStatus, _value.getValue());
        },
        std::make_tuple(deploy_value));
}

/*
 * description: 
 * brief : Interface to get the version of the table
 * param[in] : tableName : Name of the table
 * param[in] :typevalue  :  cota type for keystore/configstore
 * param[out] : response : Version of the table
 */
void ConfigurationManagerSomeIPProxy::getConfigVersion(std::string _tableName, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, std::string &_response, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::CotaType, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t> deploy_typevalue(_typevalue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_response(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                ConfigurationManager::CotaType,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2715),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName, deploy_typevalue,
        _internalCallStatus,
        deploy_response);
    _response = deploy_response.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::getConfigVersionAsync(const std::string &_tableName, const ConfigurationManager::CotaType &_typevalue, GetConfigVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::CotaType, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t> deploy_typevalue(_typevalue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_response(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                ConfigurationManager::CotaType,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2715),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName, deploy_typevalue,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _response) {
            if (_callback)
                _callback(_internalCallStatus, _response.getValue());
        },
        std::make_tuple(deploy_response));
}

/*
 * description: 
 * brief : Interface to update configuration over COTA
 * param[in] : filePath : The path of the file which is used to update the configuration
 * param[out] : updateValue : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::updateConfigRequest(std::string _filePath, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::UpdateDBStatus &_updateValue, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_filePath(_filePath, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::CotaType, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t> deploy_typevalue(_typevalue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::UpdateDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t> deploy_updateValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                ConfigurationManager::CotaType,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::UpdateDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2716),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_filePath, deploy_typevalue,
        _internalCallStatus,
        deploy_updateValue);
    _updateValue = deploy_updateValue.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::updateConfigRequestAsync(const std::string &_filePath, const ConfigurationManager::CotaType &_typevalue, UpdateConfigRequestAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_filePath(_filePath, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::CotaType, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t> deploy_typevalue(_typevalue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::UpdateDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t> deploy_updateValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >,
            CommonAPI::Deployable<
                ConfigurationManager::CotaType,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::UpdateDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2716),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_filePath, deploy_typevalue,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::UpdateDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t > _updateValue) {
            if (_callback)
                _callback(_internalCallStatus, _updateValue.getValue());
        },
        std::make_tuple(deploy_updateValue));
}

/*
 * description: 
 * brief : Interface to update the COTA completion status
 * param[in] : typevalue : Enumeration that specifies the type of configuration change
 * param[out] : value : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::setCOTACompletionStatus(ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::setCotaStateStatus &_value, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::CotaType, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t> deploy_typevalue(_typevalue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::setCotaStateStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::CotaType,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::setCotaStateStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2717),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_typevalue,
        _internalCallStatus,
        deploy_value);
    _value = deploy_value.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::setCOTACompletionStatusAsync(const ConfigurationManager::CotaType &_typevalue, SetCOTACompletionStatusAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ConfigurationManager::CotaType, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t> deploy_typevalue(_typevalue, static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::setCotaStateStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::CotaType,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::setCotaStateStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2717),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_typevalue,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::setCotaStateStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t > _value) {
            if (_callback)
                _callback(_internalCallStatus, _value.getValue());
        },
        std::make_tuple(deploy_value));
}

/*
 * description: 
 * brief : Interface to restore into Default database
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : value : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::restoreDefaultKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreDefaultStatus &_value, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::RestoreDefaultStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::RestoreDefaultStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2775),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        _internalCallStatus,
        deploy_value);
    _value = deploy_value.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::restoreDefaultKVDBAsync(const std::string &_tableName, RestoreDefaultKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::RestoreDefaultStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t> deploy_value(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::RestoreDefaultStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2775),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::RestoreDefaultStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t > _value) {
            if (_callback)
                _callback(_internalCallStatus, _value.getValue());
        },
        std::make_tuple(deploy_value));
}

/*
 * description: 
 * brief : Interface to restore into Factory database
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : value : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::restoreFactoryKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreFactoryStatus &_sValue, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::RestoreFactoryStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t> deploy_sValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::RestoreFactoryStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2776),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        _internalCallStatus,
        deploy_sValue);
    _sValue = deploy_sValue.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::restoreFactoryKVDBAsync(const std::string &_tableName, RestoreFactoryKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::RestoreFactoryStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t> deploy_sValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::RestoreFactoryStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2776),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::RestoreFactoryStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t > _sValue) {
            if (_callback)
                _callback(_internalCallStatus, _sValue.getValue());
        },
        std::make_tuple(deploy_sValue));
}

/*
 * description: 
 * brief : Interface to check database is of Factory mode
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : fValue : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::isFactoryModeKVData(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::IsFactoryStatus &_fValue, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::IsFactoryStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t> deploy_fValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::IsFactoryStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2777),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        _internalCallStatus,
        deploy_fValue);
    _fValue = deploy_fValue.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::isFactoryModeKVDataAsync(const std::string &_tableName, IsFactoryModeKVDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::IsFactoryStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t> deploy_fValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::IsFactoryStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2777),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::IsFactoryStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t > _fValue) {
            if (_callback)
                _callback(_internalCallStatus, _fValue.getValue());
        },
        std::make_tuple(deploy_fValue));
}

/*
 * description: 
 * brief : Interface to check Default database exist or not
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : sValue : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::isDefaultKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DefaultDBStatus &_sValue, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::DefaultDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t> deploy_sValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::DefaultDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2778),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        _internalCallStatus,
        deploy_sValue);
    _sValue = deploy_sValue.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::isDefaultKVDBAvlbleAsync(const std::string &_tableName, IsDefaultKVDBAvlbleAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::DefaultDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t> deploy_sValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::DefaultDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2778),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::DefaultDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t > _sValue) {
            if (_callback)
                _callback(_internalCallStatus, _sValue.getValue());
        },
        std::make_tuple(deploy_sValue));
}

/*
 * description: 
 * brief : Interface to check Factory database exist or not
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : sValue : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::isFactoryKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::FactoryDBStatus &_sValue, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::FactoryDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t> deploy_sValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::FactoryDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2779),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        _internalCallStatus,
        deploy_sValue);
    _sValue = deploy_sValue.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::isFactoryKVDBAvlbleAsync(const std::string &_tableName, IsFactoryKVDBAvlbleAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::FactoryDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t> deploy_sValue(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::FactoryDBStatus,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2779),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::FactoryDBStatus, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t > _sValue) {
            if (_callback)
                _callback(_internalCallStatus, _sValue.getValue());
        },
        std::make_tuple(deploy_sValue));
}

/*
 * description: 
 * brief : Interface to read whole configuration from table
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : status : Enumeration containing the status of the response
 */
void ConfigurationManagerSomeIPProxy::readConfigTable(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_status, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::ReadKVDBData, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t> deploy_status(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ReadKVDBData,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x277a),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        _internalCallStatus,
        deploy_status);
    _status = deploy_status.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::readConfigTableAsync(const std::string &_tableName, ReadConfigTableAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< ConfigurationManager::ReadKVDBData, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t> deploy_status(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ConfigurationManager::ReadKVDBData,
                ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x277a),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_tableName,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< ConfigurationManager::ReadKVDBData, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t > _status) {
            if (_callback)
                _callback(_internalCallStatus, _status.getValue());
        },
        std::make_tuple(deploy_status));
}

/*
 * description: 
 * brief : Interface to get the component version
 * param[in] : request : Dummy integer value
 * param[out] : compVersion : Version of the component
 */
void ConfigurationManagerSomeIPProxy::getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_compVersion(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x277b),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        _internalCallStatus,
        deploy_compVersion);
    _compVersion = deploy_compVersion.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_compVersion(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x277b),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _compVersion) {
            if (_callback)
                _callback(_internalCallStatus, _compVersion.getValue());
        },
        std::make_tuple(deploy_compVersion));
}

/*
 * description: 
 * brief : Interface to get the component identification number
 * param[in] : request : Dummy integer value
 * param[out] : componentID : Component identification number
 */
void ConfigurationManagerSomeIPProxy::getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_componentID(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x277c),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        _internalCallStatus,
        deploy_componentID);
    _componentID = deploy_componentID.getValue();
}

std::future<CommonAPI::CallStatus> ConfigurationManagerSomeIPProxy::getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_componentID(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x277c),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > _componentID) {
            if (_callback)
                _callback(_internalCallStatus, _componentID.getValue());
        },
        std::make_tuple(deploy_componentID));
}

void ConfigurationManagerSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> ConfigurationManagerSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1
