/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

class ConfigurationManager {
public:
    virtual ~ConfigurationManager() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    /*
     * description: 
     * brief : Structure to hold parameters for create Default DB method
     */
    struct CreateDefaultKVDBInfo : CommonAPI::Struct< std::string, std::string, std::string> {
    
        CreateDefaultKVDBInfo()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
        }
        CreateDefaultKVDBInfo(const std::string &_tableName, const std::string &_versionNumber, const std::string &_inputJSON)
        {
            std::get< 0>(values_) = _tableName;
            std::get< 1>(values_) = _versionNumber;
            std::get< 2>(values_) = _inputJSON;
        }
        inline const std::string &getTableName() const { return std::get< 0>(values_); }
        inline void setTableName(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getVersionNumber() const { return std::get< 1>(values_); }
        inline void setVersionNumber(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getInputJSON() const { return std::get< 2>(values_); }
        inline void setInputJSON(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline bool operator==(const CreateDefaultKVDBInfo& _other) const {
        return (getTableName() == _other.getTableName() && getVersionNumber() == _other.getVersionNumber() && getInputJSON() == _other.getInputJSON());
        }
        inline bool operator!=(const CreateDefaultKVDBInfo &_other) const {
            return !((*this) == _other);
        }
    
    };
    /*
     * description: 
     * brief : Structure to hold parameters for Modify DB method
     */
    struct ModifyKVDBInfo : CommonAPI::Struct< std::string, std::string, std::string, std::string, std::string> {
    
        ModifyKVDBInfo()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
            std::get< 3>(values_) = "";
            std::get< 4>(values_) = "";
        }
        ModifyKVDBInfo(const std::string &_tableName, const std::string &_versionNumber, const std::string &_key, const std::string &_subKey, const std::string &_data)
        {
            std::get< 0>(values_) = _tableName;
            std::get< 1>(values_) = _versionNumber;
            std::get< 2>(values_) = _key;
            std::get< 3>(values_) = _subKey;
            std::get< 4>(values_) = _data;
        }
        inline const std::string &getTableName() const { return std::get< 0>(values_); }
        inline void setTableName(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getVersionNumber() const { return std::get< 1>(values_); }
        inline void setVersionNumber(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getKey() const { return std::get< 2>(values_); }
        inline void setKey(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline const std::string &getSubKey() const { return std::get< 3>(values_); }
        inline void setSubKey(const std::string &_value) { std::get< 3>(values_) = _value; }
        inline const std::string &getData() const { return std::get< 4>(values_); }
        inline void setData(const std::string &_value) { std::get< 4>(values_) = _value; }
        inline bool operator==(const ModifyKVDBInfo& _other) const {
        return (getTableName() == _other.getTableName() && getVersionNumber() == _other.getVersionNumber() && getKey() == _other.getKey() && getSubKey() == _other.getSubKey() && getData() == _other.getData());
        }
        inline bool operator!=(const ModifyKVDBInfo &_other) const {
            return !((*this) == _other);
        }
    
    };
    /*
     * description: 
     * brief : Structure to hold parameters for Read DB method
     */
    struct ReadKVDBInfo : CommonAPI::Struct< std::string, std::string, std::string> {
    
        ReadKVDBInfo()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
        }
        ReadKVDBInfo(const std::string &_tableName, const std::string &_key, const std::string &_subKey)
        {
            std::get< 0>(values_) = _tableName;
            std::get< 1>(values_) = _key;
            std::get< 2>(values_) = _subKey;
        }
        inline const std::string &getTableName() const { return std::get< 0>(values_); }
        inline void setTableName(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getKey() const { return std::get< 1>(values_); }
        inline void setKey(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getSubKey() const { return std::get< 2>(values_); }
        inline void setSubKey(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline bool operator==(const ReadKVDBInfo& _other) const {
        return (getTableName() == _other.getTableName() && getKey() == _other.getKey() && getSubKey() == _other.getSubKey());
        }
        inline bool operator!=(const ReadKVDBInfo &_other) const {
            return !((*this) == _other);
        }
    
    };
    
    struct ReadStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            READ_SUCCESS = 0,
            READ_FAILED = 1
        };
    
        ReadStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::READ_SUCCESS)) {}
        ReadStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::READ_SUCCESS):
                case static_cast< uint8_t>(Literal::READ_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const ReadStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const ReadStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const ReadStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const ReadStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const ReadStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const ReadStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::READ_SUCCESS): return "READ_SUCCESS";
            case static_cast< uint8_t>(Literal::READ_FAILED): return "READ_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    /*
     * description: 
     * brief : Structure to hold output parameter for Modify DB method
     */
    struct ReadKVDBData : CommonAPI::Struct< std::string, ReadStatus> {
    
        ReadKVDBData()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = ReadStatus();
        }
        ReadKVDBData(const std::string &_data, const ReadStatus &_sValue)
        {
            std::get< 0>(values_) = _data;
            std::get< 1>(values_) = _sValue;
        }
        inline const std::string &getData() const { return std::get< 0>(values_); }
        inline void setData(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const ReadStatus &getSValue() const { return std::get< 1>(values_); }
        inline void setSValue(const ReadStatus &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const ReadKVDBData& _other) const {
        return (getData() == _other.getData() && getSValue() == _other.getSValue());
        }
        inline bool operator!=(const ReadKVDBData &_other) const {
            return !((*this) == _other);
        }
    
    };
    /*
     * description: 
     * brief : Structure to hold parameter for Delete DB method
     */
    struct DeleteKVDBInfo : CommonAPI::Struct< std::string, std::string, std::string, std::string> {
    
        DeleteKVDBInfo()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
            std::get< 3>(values_) = "";
        }
        DeleteKVDBInfo(const std::string &_tableName, const std::string &_key, const std::string &_subKey, const std::string &_versionNumber)
        {
            std::get< 0>(values_) = _tableName;
            std::get< 1>(values_) = _key;
            std::get< 2>(values_) = _subKey;
            std::get< 3>(values_) = _versionNumber;
        }
        inline const std::string &getTableName() const { return std::get< 0>(values_); }
        inline void setTableName(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getKey() const { return std::get< 1>(values_); }
        inline void setKey(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getSubKey() const { return std::get< 2>(values_); }
        inline void setSubKey(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline const std::string &getVersionNumber() const { return std::get< 3>(values_); }
        inline void setVersionNumber(const std::string &_value) { std::get< 3>(values_) = _value; }
        inline bool operator==(const DeleteKVDBInfo& _other) const {
        return (getTableName() == _other.getTableName() && getKey() == _other.getKey() && getSubKey() == _other.getSubKey() && getVersionNumber() == _other.getVersionNumber());
        }
        inline bool operator!=(const DeleteKVDBInfo &_other) const {
            return !((*this) == _other);
        }
    
    };
    
    struct CreateDBStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            CREATEDB_SUCCESS = 0,
            CREATEDB_FAILED = 1
        };
    
        CreateDBStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::CREATEDB_SUCCESS)) {}
        CreateDBStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::CREATEDB_SUCCESS):
                case static_cast< uint8_t>(Literal::CREATEDB_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const CreateDBStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const CreateDBStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const CreateDBStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const CreateDBStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const CreateDBStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const CreateDBStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::CREATEDB_SUCCESS): return "CREATEDB_SUCCESS";
            case static_cast< uint8_t>(Literal::CREATEDB_FAILED): return "CREATEDB_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct ModifyStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            MODIFY_SUCCESS = 0,
            MODIFY_FAILED = 1
        };
    
        ModifyStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::MODIFY_SUCCESS)) {}
        ModifyStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::MODIFY_SUCCESS):
                case static_cast< uint8_t>(Literal::MODIFY_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const ModifyStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const ModifyStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const ModifyStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const ModifyStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const ModifyStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const ModifyStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::MODIFY_SUCCESS): return "MODIFY_SUCCESS";
            case static_cast< uint8_t>(Literal::MODIFY_FAILED): return "MODIFY_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct DeleteStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            DELETE_SUCCESS = 0,
            DELETE_FAILED = 1
        };
    
        DeleteStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::DELETE_SUCCESS)) {}
        DeleteStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::DELETE_SUCCESS):
                case static_cast< uint8_t>(Literal::DELETE_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const DeleteStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const DeleteStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const DeleteStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const DeleteStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const DeleteStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const DeleteStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::DELETE_SUCCESS): return "DELETE_SUCCESS";
            case static_cast< uint8_t>(Literal::DELETE_FAILED): return "DELETE_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct UpdateDBStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            UPDATE_SUCCESS = 0,
            UPDATE_FAILED = 1
        };
    
        UpdateDBStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::UPDATE_SUCCESS)) {}
        UpdateDBStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::UPDATE_SUCCESS):
                case static_cast< uint8_t>(Literal::UPDATE_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const UpdateDBStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const UpdateDBStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const UpdateDBStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const UpdateDBStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const UpdateDBStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const UpdateDBStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::UPDATE_SUCCESS): return "UPDATE_SUCCESS";
            case static_cast< uint8_t>(Literal::UPDATE_FAILED): return "UPDATE_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct CotaType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            KEYSTORE_INDIVIDUAL = 0,
            CONFIGSTORE_INDIVIDUAL = 1,
            KEYSTORE_MULTIPLE = 2,
            CONFIGSTORE_MULTIPLE = 3
        };
    
        CotaType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::KEYSTORE_INDIVIDUAL)) {}
        CotaType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::KEYSTORE_INDIVIDUAL):
                case static_cast< uint8_t>(Literal::CONFIGSTORE_INDIVIDUAL):
                case static_cast< uint8_t>(Literal::KEYSTORE_MULTIPLE):
                case static_cast< uint8_t>(Literal::CONFIGSTORE_MULTIPLE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const CotaType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const CotaType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const CotaType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const CotaType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const CotaType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const CotaType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::KEYSTORE_INDIVIDUAL): return "KEYSTORE_INDIVIDUAL";
            case static_cast< uint8_t>(Literal::CONFIGSTORE_INDIVIDUAL): return "CONFIGSTORE_INDIVIDUAL";
            case static_cast< uint8_t>(Literal::KEYSTORE_MULTIPLE): return "KEYSTORE_MULTIPLE";
            case static_cast< uint8_t>(Literal::CONFIGSTORE_MULTIPLE): return "CONFIGSTORE_MULTIPLE";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct setCotaStateStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SETCOTASTATE_SUCCESS = 0,
            SETCOTASTATE_FAILURE = 1
        };
    
        setCotaStateStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SETCOTASTATE_SUCCESS)) {}
        setCotaStateStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SETCOTASTATE_SUCCESS):
                case static_cast< uint8_t>(Literal::SETCOTASTATE_FAILURE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const setCotaStateStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const setCotaStateStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const setCotaStateStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const setCotaStateStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const setCotaStateStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const setCotaStateStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SETCOTASTATE_SUCCESS): return "SETCOTASTATE_SUCCESS";
            case static_cast< uint8_t>(Literal::SETCOTASTATE_FAILURE): return "SETCOTASTATE_FAILURE";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct RestoreDefaultStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            RESTORE_SUCCESS = 0,
            RESTORE_FAILED = 1
        };
    
        RestoreDefaultStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::RESTORE_SUCCESS)) {}
        RestoreDefaultStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::RESTORE_SUCCESS):
                case static_cast< uint8_t>(Literal::RESTORE_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const RestoreDefaultStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const RestoreDefaultStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const RestoreDefaultStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const RestoreDefaultStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const RestoreDefaultStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const RestoreDefaultStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::RESTORE_SUCCESS): return "RESTORE_SUCCESS";
            case static_cast< uint8_t>(Literal::RESTORE_FAILED): return "RESTORE_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct RestoreFactoryStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            RESTORE_FACTORYSUCCESS = 0,
            RESTORE_FACTORYFAILED = 1
        };
    
        RestoreFactoryStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::RESTORE_FACTORYSUCCESS)) {}
        RestoreFactoryStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::RESTORE_FACTORYSUCCESS):
                case static_cast< uint8_t>(Literal::RESTORE_FACTORYFAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const RestoreFactoryStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const RestoreFactoryStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const RestoreFactoryStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const RestoreFactoryStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const RestoreFactoryStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const RestoreFactoryStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::RESTORE_FACTORYSUCCESS): return "RESTORE_FACTORYSUCCESS";
            case static_cast< uint8_t>(Literal::RESTORE_FACTORYFAILED): return "RESTORE_FACTORYFAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct IsFactoryStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            FACTORYDB_SUCCESS = 0,
            FACTORYDB_FAILED = 1
        };
    
        IsFactoryStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::FACTORYDB_SUCCESS)) {}
        IsFactoryStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::FACTORYDB_SUCCESS):
                case static_cast< uint8_t>(Literal::FACTORYDB_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const IsFactoryStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const IsFactoryStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const IsFactoryStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const IsFactoryStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const IsFactoryStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const IsFactoryStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::FACTORYDB_SUCCESS): return "FACTORYDB_SUCCESS";
            case static_cast< uint8_t>(Literal::FACTORYDB_FAILED): return "FACTORYDB_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct DefaultDBStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            DBEXIST_SUCCESS = 0,
            DBEXIST_FAILED = 1
        };
    
        DefaultDBStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::DBEXIST_SUCCESS)) {}
        DefaultDBStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::DBEXIST_SUCCESS):
                case static_cast< uint8_t>(Literal::DBEXIST_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const DefaultDBStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const DefaultDBStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const DefaultDBStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const DefaultDBStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const DefaultDBStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const DefaultDBStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::DBEXIST_SUCCESS): return "DBEXIST_SUCCESS";
            case static_cast< uint8_t>(Literal::DBEXIST_FAILED): return "DBEXIST_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct FactoryDBStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            DBEXIST_SUCCESS = 0,
            DBEXIST_FAILED = 1
        };
    
        FactoryDBStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::DBEXIST_SUCCESS)) {}
        FactoryDBStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::DBEXIST_SUCCESS):
                case static_cast< uint8_t>(Literal::DBEXIST_FAILED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const FactoryDBStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const FactoryDBStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const FactoryDBStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const FactoryDBStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const FactoryDBStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const FactoryDBStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::DBEXIST_SUCCESS): return "DBEXIST_SUCCESS";
            case static_cast< uint8_t>(Literal::DBEXIST_FAILED): return "DBEXIST_FAILED";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* ConfigurationManager::getInterface() {
    return ("commonapi.toscore.cmsservice.ConfigurationManager:v1_0");
}

CommonAPI::Version ConfigurationManager::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}

/*
 * description: 
 * brief : Structure to hold parameters for create Default DB method
 */
/*
 * description: 
 * brief : Structure to hold parameters for Modify DB method
 */
/*
 * description: 
 * brief : Structure to hold parameters for Read DB method
 */
/*
 * description: 
 * brief : Structure to hold output parameter for Modify DB method
 */
/*
 * description: 
 * brief : Structure to hold parameter for Delete DB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of createDefaultKVDB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of modifyKVDB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of readKVDB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of deleteKVDB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of  updateConfigRequest method
 */
/*
 * description: 
 * brief : Enumeration to hold the cota type for  updateConfigRequest method
 */
/*
 * description: 
 * brief : Enumeration to hold status of  setCOTACompletionState method
 */
/*
 * description: 
 * brief : Enumeration to hold status of restoreDefaultKVDB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of restoreFactoryKVDB method
 */
/*
 * description: 
 * brief : Enumeration to hold status of isFactoryModeKVData method
 */
/*
 * description: 
 * brief : Enumeration to hold status of Check Whether isDefaultKVDBAvlble method
 */
/*
 * description: 
 * brief : Enumeration to hold status of Check Whether isFactoryKVDBAvlble method
 */

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_HPP_
