/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

/**
 * Provides a default implementation for ConfigurationManagerStubRemoteEvent and
 * ConfigurationManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT ConfigurationManagerStubDefault
    : public virtual ConfigurationManagerStub {
public:
    COMMONAPI_EXPORT ConfigurationManagerStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(ConfigurationManager::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT ConfigurationManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr< ConfigurationManagerStubAdapter> &_adapter) {
        CommonAPI::Stub<ConfigurationManagerStubAdapter, ConfigurationManagerStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * brief : Interface to create Default database
     * param[in] : input : Structure containing the database details needed to create a new table
     * param[out] : output : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void createDefaultKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::CreateDefaultKVDBInfo _input, createDefaultKVDBReply_t _reply) {
        (void)_client;
        (void)_input;
        ConfigurationManager::CreateDBStatus output = ConfigurationManager::CreateDBStatus::CREATEDB_SUCCESS;
        if (!output.validate()) {
            return;
        }
        _reply(output);
    }
    /*
     * description: 
     * brief : Interface to write/update database
     * param[in] : input : Structure containing the database details needed to modify the data
     * param[out] : value : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void modifyKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::ModifyKVDBInfo _input, modifyKVDBReply_t _reply) {
        (void)_client;
        (void)_input;
        ConfigurationManager::ModifyStatus value = ConfigurationManager::ModifyStatus::MODIFY_SUCCESS;
        if (!value.validate()) {
            return;
        }
        _reply(value);
    }
    /*
     * description: 
     * brief : Interface to read data from database
     * param[in] : getValue : Structure containing the database details needed to read the data
     * param[out] : statusValue : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void readKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::ReadKVDBInfo _getValue, readKVDBReply_t _reply) {
        (void)_client;
        (void)_getValue;
        ConfigurationManager::ReadKVDBData statusValue = {};
        _reply(statusValue);
    }
    /*
     * description: 
     * brief : Interface to delete data from database
     * param[in] : deletValue : Structure containing the database details needed to delete the data
     * param[out] : value : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void deleteKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::DeleteKVDBInfo _deletValue, deleteKVDBReply_t _reply) {
        (void)_client;
        (void)_deletValue;
        ConfigurationManager::DeleteStatus value = ConfigurationManager::DeleteStatus::DELETE_SUCCESS;
        if (!value.validate()) {
            return;
        }
        _reply(value);
    }
    /*
     * description: 
     * brief : Interface to get the version of the table
     * param[in] : tableName : Name of the table
     * param[in] :typevalue  :  cota type for keystore/configstore
     * param[out] : response : Version of the table
     */
    COMMONAPI_EXPORT virtual void getConfigVersion(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, ConfigurationManager::CotaType _typevalue, getConfigVersionReply_t _reply) {
        (void)_client;
        (void)_tableName;
        (void)_typevalue;
        std::string response = "";
        _reply(response);
    }
    /*
     * description: 
     * brief : Interface to update configuration over COTA
     * param[in] : filePath : The path of the file which is used to update the configuration
     * param[out] : updateValue : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void updateConfigRequest(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _filePath, ConfigurationManager::CotaType _typevalue, updateConfigRequestReply_t _reply) {
        (void)_client;
        (void)_filePath;
        (void)_typevalue;
        ConfigurationManager::UpdateDBStatus updateValue = ConfigurationManager::UpdateDBStatus::UPDATE_SUCCESS;
        if (!updateValue.validate()) {
            return;
        }
        _reply(updateValue);
    }
    /*
     * description: 
     * brief : Interface to update the COTA completion status
     * param[in] : typevalue : Enumeration that specifies the type of configuration change
     * param[out] : value : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void setCOTACompletionStatus(const std::shared_ptr<CommonAPI::ClientId> _client, ConfigurationManager::CotaType _typevalue, setCOTACompletionStatusReply_t _reply) {
        (void)_client;
        (void)_typevalue;
        ConfigurationManager::setCotaStateStatus value = ConfigurationManager::setCotaStateStatus::SETCOTASTATE_SUCCESS;
        if (!value.validate()) {
            return;
        }
        _reply(value);
    }
    /*
     * description: 
     * brief : Interface to restore into Default database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void restoreDefaultKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, restoreDefaultKVDBReply_t _reply) {
        (void)_client;
        (void)_tableName;
        ConfigurationManager::RestoreDefaultStatus value = ConfigurationManager::RestoreDefaultStatus::RESTORE_SUCCESS;
        if (!value.validate()) {
            return;
        }
        _reply(value);
    }
    /*
     * description: 
     * brief : Interface to restore into Factory database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void restoreFactoryKVDB(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, restoreFactoryKVDBReply_t _reply) {
        (void)_client;
        (void)_tableName;
        ConfigurationManager::RestoreFactoryStatus sValue = ConfigurationManager::RestoreFactoryStatus::RESTORE_FACTORYSUCCESS;
        if (!sValue.validate()) {
            return;
        }
        _reply(sValue);
    }
    /*
     * description: 
     * brief : Interface to check database is of Factory mode
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : fValue : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void isFactoryModeKVData(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, isFactoryModeKVDataReply_t _reply) {
        (void)_client;
        (void)_tableName;
        ConfigurationManager::IsFactoryStatus fValue = ConfigurationManager::IsFactoryStatus::FACTORYDB_SUCCESS;
        if (!fValue.validate()) {
            return;
        }
        _reply(fValue);
    }
    /*
     * description: 
     * brief : Interface to check Default database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void isDefaultKVDBAvlble(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, isDefaultKVDBAvlbleReply_t _reply) {
        (void)_client;
        (void)_tableName;
        ConfigurationManager::DefaultDBStatus sValue = ConfigurationManager::DefaultDBStatus::DBEXIST_SUCCESS;
        if (!sValue.validate()) {
            return;
        }
        _reply(sValue);
    }
    /*
     * description: 
     * brief : Interface to check Factory database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void isFactoryKVDBAvlble(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, isFactoryKVDBAvlbleReply_t _reply) {
        (void)_client;
        (void)_tableName;
        ConfigurationManager::FactoryDBStatus sValue = ConfigurationManager::FactoryDBStatus::DBEXIST_SUCCESS;
        if (!sValue.validate()) {
            return;
        }
        _reply(sValue);
    }
    /*
     * description: 
     * brief : Interface to read whole configuration from table
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : status : Enumeration containing the status of the response
     */
    COMMONAPI_EXPORT virtual void readConfigTable(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _tableName, readConfigTableReply_t _reply) {
        (void)_client;
        (void)_tableName;
        ConfigurationManager::ReadKVDBData status = {};
        _reply(status);
    }
    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    COMMONAPI_EXPORT virtual void getVersion(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getVersionReply_t _reply) {
        (void)_client;
        (void)_request;
        std::string compVersion = "";
        _reply(compVersion);
    }
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : componentID : Component identification number
     */
    COMMONAPI_EXPORT virtual void getComponentID(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getComponentIDReply_t _reply) {
        (void)_client;
        (void)_request;
        uint8_t componentID = 0u;
        _reply(componentID);
    }
    /*
     * description: 
     * brief : Event to get update in latest table of a database
     * param[out] : tableName : Name of the table corresponding to a module
     */
    COMMONAPI_EXPORT virtual void fireChangeDataNotifyEvent(const std::string &_tableName) {
        ConfigurationManagerStub::fireChangeDataNotifyEvent(_tableName);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual ConfigurationManagerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(ConfigurationManagerStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        ConfigurationManagerStubDefault *defaultStub_;
    };
protected:
    ConfigurationManagerStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_STUB_DEFAULT
