/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_CONFIGURATION_MANAGER_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerStub.hpp>
#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

template <typename _Stub = ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub, typename... _Stubs>
class ConfigurationManagerSomeIPStubAdapterInternal
    : public virtual ConfigurationManagerStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< ConfigurationManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> ConfigurationManagerSomeIPStubAdapterHelper;

    ~ConfigurationManagerSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        ConfigurationManagerSomeIPStubAdapterHelper::deinit();
    }

    /*
     * description: 
     * brief : Event to get update in latest table of a database
     * param[out] : tableName : Name of the table corresponding to a module
     */
    void fireChangeDataNotifyEvent(const std::string &_tableName);

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        CommonAPI::Version
    > getConfigurationManagerInterfaceVersionStubDispatcher;

    /*
     * description: 
     * brief : Interface to create Default database
     * param[in] : input : Structure containing the database details needed to create a new table
     * param[out] : output : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< ConfigurationManager::CreateDefaultKVDBInfo>,
        std::tuple< ConfigurationManager::CreateDBStatus>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t>
    > createDefaultKVDBStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to write/update database
     * param[in] : input : Structure containing the database details needed to modify the data
     * param[out] : value : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< ConfigurationManager::ModifyKVDBInfo>,
        std::tuple< ConfigurationManager::ModifyStatus>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t>
    > modifyKVDBStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to read data from database
     * param[in] : getValue : Structure containing the database details needed to read the data
     * param[out] : statusValue : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< ConfigurationManager::ReadKVDBInfo>,
        std::tuple< ConfigurationManager::ReadKVDBData>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t>
    > readKVDBStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to delete data from database
     * param[in] : deletValue : Structure containing the database details needed to delete the data
     * param[out] : value : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< ConfigurationManager::DeleteKVDBInfo>,
        std::tuple< ConfigurationManager::DeleteStatus>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t>
    > deleteKVDBStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to get the version of the table
     * param[in] : tableName : Name of the table
     * param[in] :typevalue  :  cota type for keystore/configstore
     * param[out] : response : Version of the table
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string, ConfigurationManager::CotaType>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > getConfigVersionStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to update configuration over COTA
     * param[in] : filePath : The path of the file which is used to update the configuration
     * param[out] : updateValue : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string, ConfigurationManager::CotaType>,
        std::tuple< ConfigurationManager::UpdateDBStatus>,
        std::tuple< CommonAPI::SomeIP::StringDeployment, ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t>
    > updateConfigRequestStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to update the COTA completion status
     * param[in] : typevalue : Enumeration that specifies the type of configuration change
     * param[out] : value : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< ConfigurationManager::CotaType>,
        std::tuple< ConfigurationManager::setCotaStateStatus>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t>
    > setCOTACompletionStatusStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to restore into Default database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string>,
        std::tuple< ConfigurationManager::RestoreDefaultStatus>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t>
    > restoreDefaultKVDBStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to restore into Factory database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string>,
        std::tuple< ConfigurationManager::RestoreFactoryStatus>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t>
    > restoreFactoryKVDBStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to check database is of Factory mode
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : fValue : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string>,
        std::tuple< ConfigurationManager::IsFactoryStatus>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t>
    > isFactoryModeKVDataStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to check Default database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string>,
        std::tuple< ConfigurationManager::DefaultDBStatus>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t>
    > isDefaultKVDBAvlbleStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to check Factory database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string>,
        std::tuple< ConfigurationManager::FactoryDBStatus>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t>
    > isFactoryKVDBAvlbleStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to read whole configuration from table
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : status : Enumeration containing the status of the response
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< std::string>,
        std::tuple< ConfigurationManager::ReadKVDBData>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t>
    > readConfigTableStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< int32_t>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > getVersionStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : componentID : Component identification number
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub,
        std::tuple< int32_t>,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > getComponentIDStubDispatcher;
    
    ConfigurationManagerSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        ConfigurationManagerSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< ConfigurationManagerStub>(_stub)),
        getConfigurationManagerInterfaceVersionStubDispatcher(&ConfigurationManagerStub::lockInterfaceVersionAttribute, &ConfigurationManagerStub::getInterfaceVersion, false, true),
        createDefaultKVDBStubDispatcher(
            &ConfigurationManagerStub::createDefaultKVDB,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDefaultKVDBInfoDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CreateDBStatusDeployment_t* >(nullptr)))
        
        ,
        modifyKVDBStubDispatcher(
            &ConfigurationManagerStub::modifyKVDB,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyKVDBInfoDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ModifyStatusDeployment_t* >(nullptr)))
        
        ,
        readKVDBStubDispatcher(
            &ConfigurationManagerStub::readKVDB,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBInfoDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t* >(nullptr)))
        
        ,
        deleteKVDBStubDispatcher(
            &ConfigurationManagerStub::deleteKVDB,
            false,
            _stub->hasElement(3),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteKVDBInfoDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DeleteStatusDeployment_t* >(nullptr)))
        
        ,
        getConfigVersionStubDispatcher(
            &ConfigurationManagerStub::getConfigVersion,
            false,
            _stub->hasElement(4),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        updateConfigRequestStubDispatcher(
            &ConfigurationManagerStub::updateConfigRequest,
            false,
            _stub->hasElement(5),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr), static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::UpdateDBStatusDeployment_t* >(nullptr)))
        
        ,
        setCOTACompletionStatusStubDispatcher(
            &ConfigurationManagerStub::setCOTACompletionStatus,
            false,
            _stub->hasElement(6),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::CotaTypeDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::setCotaStateStatusDeployment_t* >(nullptr)))
        
        ,
        restoreDefaultKVDBStubDispatcher(
            &ConfigurationManagerStub::restoreDefaultKVDB,
            false,
            _stub->hasElement(7),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreDefaultStatusDeployment_t* >(nullptr)))
        
        ,
        restoreFactoryKVDBStubDispatcher(
            &ConfigurationManagerStub::restoreFactoryKVDB,
            false,
            _stub->hasElement(8),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::RestoreFactoryStatusDeployment_t* >(nullptr)))
        
        ,
        isFactoryModeKVDataStubDispatcher(
            &ConfigurationManagerStub::isFactoryModeKVData,
            false,
            _stub->hasElement(9),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::IsFactoryStatusDeployment_t* >(nullptr)))
        
        ,
        isDefaultKVDBAvlbleStubDispatcher(
            &ConfigurationManagerStub::isDefaultKVDBAvlble,
            false,
            _stub->hasElement(10),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::DefaultDBStatusDeployment_t* >(nullptr)))
        
        ,
        isFactoryKVDBAvlbleStubDispatcher(
            &ConfigurationManagerStub::isFactoryKVDBAvlble,
            false,
            _stub->hasElement(11),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::FactoryDBStatusDeployment_t* >(nullptr)))
        
        ,
        readConfigTableStubDispatcher(
            &ConfigurationManagerStub::readConfigTable,
            false,
            _stub->hasElement(12),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadKVDBDataDeployment_t* >(nullptr)))
        
        ,
        getVersionStubDispatcher(
            &ConfigurationManagerStub::getVersion,
            false,
            _stub->hasElement(13),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        getComponentIDStubDispatcher(
            &ConfigurationManagerStub::getComponentID,
            false,
            _stub->hasElement(14),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
    {
        /*
         * description: 
         * brief : Interface to create Default database
         * param[in] : input : Structure containing the database details needed to create a new table
         * param[out] : output : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2711) }, &createDefaultKVDBStubDispatcher );
        /*
         * description: 
         * brief : Interface to write/update database
         * param[in] : input : Structure containing the database details needed to modify the data
         * param[out] : value : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2712) }, &modifyKVDBStubDispatcher );
        /*
         * description: 
         * brief : Interface to read data from database
         * param[in] : getValue : Structure containing the database details needed to read the data
         * param[out] : statusValue : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2713) }, &readKVDBStubDispatcher );
        /*
         * description: 
         * brief : Interface to delete data from database
         * param[in] : deletValue : Structure containing the database details needed to delete the data
         * param[out] : value : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2714) }, &deleteKVDBStubDispatcher );
        /*
         * description: 
         * brief : Interface to get the version of the table
         * param[in] : tableName : Name of the table
         * param[in] :typevalue  :  cota type for keystore/configstore
         * param[out] : response : Version of the table
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2715) }, &getConfigVersionStubDispatcher );
        /*
         * description: 
         * brief : Interface to update configuration over COTA
         * param[in] : filePath : The path of the file which is used to update the configuration
         * param[out] : updateValue : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2716) }, &updateConfigRequestStubDispatcher );
        /*
         * description: 
         * brief : Interface to update the COTA completion status
         * param[in] : typevalue : Enumeration that specifies the type of configuration change
         * param[out] : value : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2717) }, &setCOTACompletionStatusStubDispatcher );
        /*
         * description: 
         * brief : Interface to restore into Default database
         * param[in] : tableName : Name of the table corresponding to a module
         * param[out] : value : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2775) }, &restoreDefaultKVDBStubDispatcher );
        /*
         * description: 
         * brief : Interface to restore into Factory database
         * param[in] : tableName : Name of the table corresponding to a module
         * param[out] : value : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2776) }, &restoreFactoryKVDBStubDispatcher );
        /*
         * description: 
         * brief : Interface to check database is of Factory mode
         * param[in] : tableName : Name of the table corresponding to a module
         * param[out] : fValue : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2777) }, &isFactoryModeKVDataStubDispatcher );
        /*
         * description: 
         * brief : Interface to check Default database exist or not
         * param[in] : tableName : Name of the table corresponding to a module
         * param[out] : sValue : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2778) }, &isDefaultKVDBAvlbleStubDispatcher );
        /*
         * description: 
         * brief : Interface to check Factory database exist or not
         * param[in] : tableName : Name of the table corresponding to a module
         * param[out] : sValue : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2779) }, &isFactoryKVDBAvlbleStubDispatcher );
        /*
         * description: 
         * brief : Interface to read whole configuration from table
         * param[in] : tableName : Name of the table corresponding to a module
         * param[out] : status : Enumeration containing the status of the response
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x277a) }, &readConfigTableStubDispatcher );
        /*
         * description: 
         * brief : Interface to get the component version
         * param[in] : request : Dummy integer value
         * param[out] : compVersion : Version of the component
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x277b) }, &getVersionStubDispatcher );
        /*
         * description: 
         * brief : Interface to get the component identification number
         * param[in] : request : Dummy integer value
         * param[out] : componentID : Component identification number
         */
        ConfigurationManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x277c) }, &getComponentIDStubDispatcher );
        // Provided events/fields
        {
            std::set<CommonAPI::SomeIP::eventgroup_id_t> itsEventGroups;
            itsEventGroups.insert(CommonAPI::SomeIP::eventgroup_id_t(0x88b9));
            CommonAPI::SomeIP::StubAdapter::registerEvent(CommonAPI::SomeIP::event_id_t(0x80e9), itsEventGroups, CommonAPI::SomeIP::event_type_e::ET_EVENT, CommonAPI::SomeIP::reliability_type_e::RT_RELIABLE);
        }
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};

/*
 * description: 
 * brief : Event to get update in latest table of a database
 * param[out] : tableName : Name of the table corresponding to a module
 */
template <typename _Stub, typename... _Stubs>
void ConfigurationManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::fireChangeDataNotifyEvent(const std::string &_tableName) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deployed_tableName(_tableName, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::StubEventHelper<CommonAPI::SomeIP::SerializableArguments<  CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > 
    >>
        ::sendEvent(
            *this,
            CommonAPI::SomeIP::event_id_t(0x80e9),
            false,
             deployed_tableName 
    );
}


template <typename _Stub, typename... _Stubs>
void ConfigurationManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void ConfigurationManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub, typename... _Stubs>
class ConfigurationManagerSomeIPStubAdapter
    : public ConfigurationManagerSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    ConfigurationManagerSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          ConfigurationManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_SOMEIP_STUB_ADAPTER_HPP_
