/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_SOMEIP_DEPLOYMENT_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {
namespace ConfigurationManager_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> CreateDBStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ModifyStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ReadStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DeleteStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> UpdateDBStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> CotaTypeDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> setCotaStateStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> RestoreDefaultStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> RestoreFactoryStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> IsFactoryStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DefaultDBStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> FactoryDBStatusDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment
> CreateDefaultKVDBInfoDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment
> ModifyKVDBInfoDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment
> ReadKVDBInfoDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    ::v1::commonapi::toscore::cmsservice::ConfigurationManager_::ReadStatusDeployment_t
> ReadKVDBDataDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment,
    CommonAPI::SomeIP::StringDeployment
> DeleteKVDBInfoDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace ConfigurationManager_
} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_SOMEIP_DEPLOYMENT_HPP_
