/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_PROXY_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_PROXY_HPP_

#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

template <typename ... _AttributeExtensions>
class ConfigurationManagerProxy
    : virtual public ConfigurationManager,
      virtual public ConfigurationManagerProxyBase,
      virtual public _AttributeExtensions... {
public:
    ConfigurationManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ConfigurationManagerProxy();

    typedef ConfigurationManager InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * brief : Interface to create Default database
     * param[in] : input : Structure containing the database details needed to create a new table
     * param[out] : output : Enumeration containing the status of the response
     * Calls createDefaultKVDB with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void createDefaultKVDB(ConfigurationManager::CreateDefaultKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::CreateDBStatus &_output, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls createDefaultKVDB with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> createDefaultKVDBAsync(const ConfigurationManager::CreateDefaultKVDBInfo &_input, CreateDefaultKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to write/update database
     * param[in] : input : Structure containing the database details needed to modify the data
     * param[out] : value : Enumeration containing the status of the response
     * Calls modifyKVDB with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void modifyKVDB(ConfigurationManager::ModifyKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ModifyStatus &_value, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls modifyKVDB with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> modifyKVDBAsync(const ConfigurationManager::ModifyKVDBInfo &_input, ModifyKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to read data from database
     * param[in] : getValue : Structure containing the database details needed to read the data
     * param[out] : statusValue : Enumeration containing the status of the response
     * Calls readKVDB with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void readKVDB(ConfigurationManager::ReadKVDBInfo _getValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_statusValue, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls readKVDB with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> readKVDBAsync(const ConfigurationManager::ReadKVDBInfo &_getValue, ReadKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to delete data from database
     * param[in] : deletValue : Structure containing the database details needed to delete the data
     * param[out] : value : Enumeration containing the status of the response
     * Calls deleteKVDB with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void deleteKVDB(ConfigurationManager::DeleteKVDBInfo _deletValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DeleteStatus &_value, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls deleteKVDB with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> deleteKVDBAsync(const ConfigurationManager::DeleteKVDBInfo &_deletValue, DeleteKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to get the version of the table
     * param[in] : tableName : Name of the table
     * param[in] :typevalue  :  cota type for keystore/configstore
     * param[out] : response : Version of the table
     * Calls getConfigVersion with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getConfigVersion(std::string _tableName, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, std::string &_response, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getConfigVersion with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getConfigVersionAsync(const std::string &_tableName, const ConfigurationManager::CotaType &_typevalue, GetConfigVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to update configuration over COTA
     * param[in] : filePath : The path of the file which is used to update the configuration
     * param[out] : updateValue : Enumeration containing the status of the response
     * Calls updateConfigRequest with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void updateConfigRequest(std::string _filePath, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::UpdateDBStatus &_updateValue, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls updateConfigRequest with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> updateConfigRequestAsync(const std::string &_filePath, const ConfigurationManager::CotaType &_typevalue, UpdateConfigRequestAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to update the COTA completion status
     * param[in] : typevalue : Enumeration that specifies the type of configuration change
     * param[out] : value : Enumeration containing the status of the response
     * Calls setCOTACompletionStatus with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setCOTACompletionStatus(ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::setCotaStateStatus &_value, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setCOTACompletionStatus with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setCOTACompletionStatusAsync(const ConfigurationManager::CotaType &_typevalue, SetCOTACompletionStatusAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to restore into Default database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     * Calls restoreDefaultKVDB with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void restoreDefaultKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreDefaultStatus &_value, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls restoreDefaultKVDB with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> restoreDefaultKVDBAsync(const std::string &_tableName, RestoreDefaultKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to restore into Factory database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     * Calls restoreFactoryKVDB with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void restoreFactoryKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreFactoryStatus &_sValue, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls restoreFactoryKVDB with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> restoreFactoryKVDBAsync(const std::string &_tableName, RestoreFactoryKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to check database is of Factory mode
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : fValue : Enumeration containing the status of the response
     * Calls isFactoryModeKVData with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void isFactoryModeKVData(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::IsFactoryStatus &_fValue, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls isFactoryModeKVData with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> isFactoryModeKVDataAsync(const std::string &_tableName, IsFactoryModeKVDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to check Default database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     * Calls isDefaultKVDBAvlble with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void isDefaultKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DefaultDBStatus &_sValue, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls isDefaultKVDBAvlble with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> isDefaultKVDBAvlbleAsync(const std::string &_tableName, IsDefaultKVDBAvlbleAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to check Factory database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     * Calls isFactoryKVDBAvlble with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void isFactoryKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::FactoryDBStatus &_sValue, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls isFactoryKVDBAvlble with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> isFactoryKVDBAvlbleAsync(const std::string &_tableName, IsFactoryKVDBAvlbleAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to read whole configuration from table
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : status : Enumeration containing the status of the response
     * Calls readConfigTable with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void readConfigTable(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_status, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls readConfigTable with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> readConfigTableAsync(const std::string &_tableName, ReadConfigTableAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     * Calls getVersion with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getVersion with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : componentID : Component identification number
     * Calls getComponentID with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getComponentID with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /*
     * description: 
     * brief : Event to get update in latest table of a database
     * param[out] : tableName : Name of the table corresponding to a module
     */
    /**
     * Returns the wrapper class that provides access to the broadcast ChangeDataNotify.
     */
    virtual ChangeDataNotifyEvent& getChangeDataNotifyEvent() {
        return delegate_->getChangeDataNotifyEvent();
    }



 private:
    std::shared_ptr< ConfigurationManagerProxyBase> delegate_;
};

typedef ConfigurationManagerProxy<> ConfigurationManagerProxyDefault;


//
// ConfigurationManagerProxy Implementation
//
template <typename ... _AttributeExtensions>
ConfigurationManagerProxy<_AttributeExtensions...>::ConfigurationManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ConfigurationManagerProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ConfigurationManagerProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ConfigurationManagerProxy<_AttributeExtensions...>::~ConfigurationManagerProxy() {
}

/*
 * description: 
 * brief : Interface to create Default database
 * param[in] : input : Structure containing the database details needed to create a new table
 * param[out] : output : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::createDefaultKVDB(ConfigurationManager::CreateDefaultKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::CreateDBStatus &_output, const CommonAPI::CallInfo *_info) {
    delegate_->createDefaultKVDB(_input, _internalCallStatus, _output, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::createDefaultKVDBAsync(const ConfigurationManager::CreateDefaultKVDBInfo &_input, CreateDefaultKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->createDefaultKVDBAsync(_input, _callback, _info);
}
/*
 * description: 
 * brief : Interface to write/update database
 * param[in] : input : Structure containing the database details needed to modify the data
 * param[out] : value : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::modifyKVDB(ConfigurationManager::ModifyKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ModifyStatus &_value, const CommonAPI::CallInfo *_info) {
    delegate_->modifyKVDB(_input, _internalCallStatus, _value, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::modifyKVDBAsync(const ConfigurationManager::ModifyKVDBInfo &_input, ModifyKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->modifyKVDBAsync(_input, _callback, _info);
}
/*
 * description: 
 * brief : Interface to read data from database
 * param[in] : getValue : Structure containing the database details needed to read the data
 * param[out] : statusValue : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::readKVDB(ConfigurationManager::ReadKVDBInfo _getValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_statusValue, const CommonAPI::CallInfo *_info) {
    delegate_->readKVDB(_getValue, _internalCallStatus, _statusValue, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::readKVDBAsync(const ConfigurationManager::ReadKVDBInfo &_getValue, ReadKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->readKVDBAsync(_getValue, _callback, _info);
}
/*
 * description: 
 * brief : Interface to delete data from database
 * param[in] : deletValue : Structure containing the database details needed to delete the data
 * param[out] : value : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::deleteKVDB(ConfigurationManager::DeleteKVDBInfo _deletValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DeleteStatus &_value, const CommonAPI::CallInfo *_info) {
    delegate_->deleteKVDB(_deletValue, _internalCallStatus, _value, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::deleteKVDBAsync(const ConfigurationManager::DeleteKVDBInfo &_deletValue, DeleteKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->deleteKVDBAsync(_deletValue, _callback, _info);
}
/*
 * description: 
 * brief : Interface to get the version of the table
 * param[in] : tableName : Name of the table
 * param[in] :typevalue  :  cota type for keystore/configstore
 * param[out] : response : Version of the table
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::getConfigVersion(std::string _tableName, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, std::string &_response, const CommonAPI::CallInfo *_info) {
    if (!_typevalue.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->getConfigVersion(_tableName, _typevalue, _internalCallStatus, _response, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::getConfigVersionAsync(const std::string &_tableName, const ConfigurationManager::CotaType &_typevalue, GetConfigVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_typevalue.validate()) {
        std::string response = "";
        _callback(CommonAPI::CallStatus::INVALID_VALUE, response);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->getConfigVersionAsync(_tableName, _typevalue, _callback, _info);
}
/*
 * description: 
 * brief : Interface to update configuration over COTA
 * param[in] : filePath : The path of the file which is used to update the configuration
 * param[out] : updateValue : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::updateConfigRequest(std::string _filePath, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::UpdateDBStatus &_updateValue, const CommonAPI::CallInfo *_info) {
    if (!_typevalue.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->updateConfigRequest(_filePath, _typevalue, _internalCallStatus, _updateValue, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::updateConfigRequestAsync(const std::string &_filePath, const ConfigurationManager::CotaType &_typevalue, UpdateConfigRequestAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_typevalue.validate()) {
        ConfigurationManager::UpdateDBStatus updateValue = ConfigurationManager::UpdateDBStatus::UPDATE_SUCCESS;
        _callback(CommonAPI::CallStatus::INVALID_VALUE, updateValue);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->updateConfigRequestAsync(_filePath, _typevalue, _callback, _info);
}
/*
 * description: 
 * brief : Interface to update the COTA completion status
 * param[in] : typevalue : Enumeration that specifies the type of configuration change
 * param[out] : value : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::setCOTACompletionStatus(ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::setCotaStateStatus &_value, const CommonAPI::CallInfo *_info) {
    if (!_typevalue.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->setCOTACompletionStatus(_typevalue, _internalCallStatus, _value, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::setCOTACompletionStatusAsync(const ConfigurationManager::CotaType &_typevalue, SetCOTACompletionStatusAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_typevalue.validate()) {
        ConfigurationManager::setCotaStateStatus value = ConfigurationManager::setCotaStateStatus::SETCOTASTATE_SUCCESS;
        _callback(CommonAPI::CallStatus::INVALID_VALUE, value);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->setCOTACompletionStatusAsync(_typevalue, _callback, _info);
}
/*
 * description: 
 * brief : Interface to restore into Default database
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : value : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::restoreDefaultKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreDefaultStatus &_value, const CommonAPI::CallInfo *_info) {
    delegate_->restoreDefaultKVDB(_tableName, _internalCallStatus, _value, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::restoreDefaultKVDBAsync(const std::string &_tableName, RestoreDefaultKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->restoreDefaultKVDBAsync(_tableName, _callback, _info);
}
/*
 * description: 
 * brief : Interface to restore into Factory database
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : value : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::restoreFactoryKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreFactoryStatus &_sValue, const CommonAPI::CallInfo *_info) {
    delegate_->restoreFactoryKVDB(_tableName, _internalCallStatus, _sValue, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::restoreFactoryKVDBAsync(const std::string &_tableName, RestoreFactoryKVDBAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->restoreFactoryKVDBAsync(_tableName, _callback, _info);
}
/*
 * description: 
 * brief : Interface to check database is of Factory mode
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : fValue : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::isFactoryModeKVData(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::IsFactoryStatus &_fValue, const CommonAPI::CallInfo *_info) {
    delegate_->isFactoryModeKVData(_tableName, _internalCallStatus, _fValue, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::isFactoryModeKVDataAsync(const std::string &_tableName, IsFactoryModeKVDataAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->isFactoryModeKVDataAsync(_tableName, _callback, _info);
}
/*
 * description: 
 * brief : Interface to check Default database exist or not
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : sValue : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::isDefaultKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DefaultDBStatus &_sValue, const CommonAPI::CallInfo *_info) {
    delegate_->isDefaultKVDBAvlble(_tableName, _internalCallStatus, _sValue, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::isDefaultKVDBAvlbleAsync(const std::string &_tableName, IsDefaultKVDBAvlbleAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->isDefaultKVDBAvlbleAsync(_tableName, _callback, _info);
}
/*
 * description: 
 * brief : Interface to check Factory database exist or not
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : sValue : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::isFactoryKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::FactoryDBStatus &_sValue, const CommonAPI::CallInfo *_info) {
    delegate_->isFactoryKVDBAvlble(_tableName, _internalCallStatus, _sValue, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::isFactoryKVDBAvlbleAsync(const std::string &_tableName, IsFactoryKVDBAvlbleAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->isFactoryKVDBAvlbleAsync(_tableName, _callback, _info);
}
/*
 * description: 
 * brief : Interface to read whole configuration from table
 * param[in] : tableName : Name of the table corresponding to a module
 * param[out] : status : Enumeration containing the status of the response
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::readConfigTable(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_status, const CommonAPI::CallInfo *_info) {
    delegate_->readConfigTable(_tableName, _internalCallStatus, _status, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::readConfigTableAsync(const std::string &_tableName, ReadConfigTableAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->readConfigTableAsync(_tableName, _callback, _info);
}
/*
 * description: 
 * brief : Interface to get the component version
 * param[in] : request : Dummy integer value
 * param[out] : compVersion : Version of the component
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info) {
    delegate_->getVersion(_request, _internalCallStatus, _compVersion, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getVersionAsync(_request, _callback, _info);
}
/*
 * description: 
 * brief : Interface to get the component identification number
 * param[in] : request : Dummy integer value
 * param[out] : componentID : Component identification number
 */
template <typename ... _AttributeExtensions>
void ConfigurationManagerProxy<_AttributeExtensions...>::getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info) {
    delegate_->getComponentID(_request, _internalCallStatus, _componentID, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ConfigurationManagerProxy<_AttributeExtensions...>::getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getComponentIDAsync(_request, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ConfigurationManagerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ConfigurationManagerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ConfigurationManagerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ConfigurationManagerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ConfigurationManagerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ConfigurationManagerProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_PROXY_HPP_
