/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Configuration Manager and Config Store Interface
 * brief : This interface provides methods to access configuration database
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_PROXY_BASE_HPP_
#define V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_PROXY_BASE_HPP_

#include <v1/commonapi/toscore/cmsservice/ConfigurationManager.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Event.hpp>
#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

class ConfigurationManagerProxyBase
    : virtual public CommonAPI::Proxy {
public:
    typedef CommonAPI::Event<
        std::string
    > ChangeDataNotifyEvent;

    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::CreateDBStatus&)> CreateDefaultKVDBAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::ModifyStatus&)> ModifyKVDBAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::ReadKVDBData&)> ReadKVDBAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::DeleteStatus&)> DeleteKVDBAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> GetConfigVersionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::UpdateDBStatus&)> UpdateConfigRequestAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::setCotaStateStatus&)> SetCOTACompletionStatusAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::RestoreDefaultStatus&)> RestoreDefaultKVDBAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::RestoreFactoryStatus&)> RestoreFactoryKVDBAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::IsFactoryStatus&)> IsFactoryModeKVDataAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::DefaultDBStatus&)> IsDefaultKVDBAvlbleAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::FactoryDBStatus&)> IsFactoryKVDBAvlbleAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const ConfigurationManager::ReadKVDBData&)> ReadConfigTableAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> GetVersionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&)> GetComponentIDAsyncCallback;

    /*
     * description: 
     * brief : Interface to create Default database
     * param[in] : input : Structure containing the database details needed to create a new table
     * param[out] : output : Enumeration containing the status of the response
     */
    virtual void createDefaultKVDB(ConfigurationManager::CreateDefaultKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::CreateDBStatus &_output, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> createDefaultKVDBAsync(const ConfigurationManager::CreateDefaultKVDBInfo &_input, CreateDefaultKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to write/update database
     * param[in] : input : Structure containing the database details needed to modify the data
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void modifyKVDB(ConfigurationManager::ModifyKVDBInfo _input, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ModifyStatus &_value, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> modifyKVDBAsync(const ConfigurationManager::ModifyKVDBInfo &_input, ModifyKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to read data from database
     * param[in] : getValue : Structure containing the database details needed to read the data
     * param[out] : statusValue : Enumeration containing the status of the response
     */
    virtual void readKVDB(ConfigurationManager::ReadKVDBInfo _getValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_statusValue, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> readKVDBAsync(const ConfigurationManager::ReadKVDBInfo &_getValue, ReadKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to delete data from database
     * param[in] : deletValue : Structure containing the database details needed to delete the data
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void deleteKVDB(ConfigurationManager::DeleteKVDBInfo _deletValue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DeleteStatus &_value, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> deleteKVDBAsync(const ConfigurationManager::DeleteKVDBInfo &_deletValue, DeleteKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to get the version of the table
     * param[in] : tableName : Name of the table
     * param[in] :typevalue  :  cota type for keystore/configstore
     * param[out] : response : Version of the table
     */
    virtual void getConfigVersion(std::string _tableName, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, std::string &_response, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getConfigVersionAsync(const std::string &_tableName, const ConfigurationManager::CotaType &_typevalue, GetConfigVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to update configuration over COTA
     * param[in] : filePath : The path of the file which is used to update the configuration
     * param[out] : updateValue : Enumeration containing the status of the response
     */
    virtual void updateConfigRequest(std::string _filePath, ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::UpdateDBStatus &_updateValue, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> updateConfigRequestAsync(const std::string &_filePath, const ConfigurationManager::CotaType &_typevalue, UpdateConfigRequestAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to update the COTA completion status
     * param[in] : typevalue : Enumeration that specifies the type of configuration change
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void setCOTACompletionStatus(ConfigurationManager::CotaType _typevalue, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::setCotaStateStatus &_value, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setCOTACompletionStatusAsync(const ConfigurationManager::CotaType &_typevalue, SetCOTACompletionStatusAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to restore into Default database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void restoreDefaultKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreDefaultStatus &_value, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> restoreDefaultKVDBAsync(const std::string &_tableName, RestoreDefaultKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to restore into Factory database
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : value : Enumeration containing the status of the response
     */
    virtual void restoreFactoryKVDB(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::RestoreFactoryStatus &_sValue, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> restoreFactoryKVDBAsync(const std::string &_tableName, RestoreFactoryKVDBAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to check database is of Factory mode
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : fValue : Enumeration containing the status of the response
     */
    virtual void isFactoryModeKVData(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::IsFactoryStatus &_fValue, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> isFactoryModeKVDataAsync(const std::string &_tableName, IsFactoryModeKVDataAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to check Default database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    virtual void isDefaultKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::DefaultDBStatus &_sValue, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> isDefaultKVDBAvlbleAsync(const std::string &_tableName, IsDefaultKVDBAvlbleAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to check Factory database exist or not
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : sValue : Enumeration containing the status of the response
     */
    virtual void isFactoryKVDBAvlble(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::FactoryDBStatus &_sValue, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> isFactoryKVDBAvlbleAsync(const std::string &_tableName, IsFactoryKVDBAvlbleAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to read whole configuration from table
     * param[in] : tableName : Name of the table corresponding to a module
     * param[out] : status : Enumeration containing the status of the response
     */
    virtual void readConfigTable(std::string _tableName, CommonAPI::CallStatus &_internalCallStatus, ConfigurationManager::ReadKVDBData &_status, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> readConfigTableAsync(const std::string &_tableName, ReadConfigTableAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    virtual void getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : componentID : Component identification number
     */
    virtual void getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Event to get update in latest table of a database
     * param[out] : tableName : Name of the table corresponding to a module
     */
    virtual ChangeDataNotifyEvent& getChangeDataNotifyEvent() = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSSERVICE_Configuration_Manager_PROXY_BASE_HPP_
