/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v1/commonapi/toscore/cmsservice/ConfigurationManagerSomeIPStubAdapter.hpp>
#include <v1/commonapi/toscore/cmsservice/ConfigurationManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmsservice {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createConfigurationManagerSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< ConfigurationManagerSomeIPStubAdapter<::v1::commonapi::toscore::cmsservice::ConfigurationManagerStub>>(_address, _connection, _stub);
}

void initializeConfigurationManagerSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.toscore.cmsservice.ConfigurationManager:v1_0:commonapi.toscore.cmsservice.ConfigurationManager",
         0xfa6, 0x7d6, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "commonapi.toscore.cmsservice.ConfigurationManager:v1_0",
        &createConfigurationManagerSomeIPStubAdapter);
}

INITIALIZER(registerConfigurationManagerSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeConfigurationManagerSomeIPStubAdapter);
}

} // namespace cmsservice
} // namespace toscore
} // namespace commonapi
} // namespace v1
