/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Self Diagnostic Manager Interface
 * brief : This interface provides API for client to initiate a diagnostic request.
 */
#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_PROXY_BASE_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_PROXY_BASE_HPP_

#include <v1/commonapi/toscore/sdmservice/SelfDiagnosticManager.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {

class SelfDiagnosticManagerProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&, const SelfDiagnosticManager::SetReqStatus&)> SetCustomPlatformDTCAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> PerformTCUDiagnosticsAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SelfDiagnosticManager::ClearReqStatus&)> ClearDTCAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SelfDiagnosticManager::DIDReadResult&)> ReadDIDAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const SelfDiagnosticManager::WriteDIDReqStatus&)> WriteDIDAsyncCallback;

    /*
     * description: 
     * brief : Interface to set custom DTC to platform
     * param[in] : customDTCReq : Custom DTC Information
     * param[out] : status : Status of the request
     */
    virtual void setCustomPlatformDTC(SelfDiagnosticManager::DTCSetReq _customDTCReq, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::SetReqStatus &_status, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> setCustomPlatformDTCAsync(const SelfDiagnosticManager::DTCSetReq &_customDTCReq, SetCustomPlatformDTCAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
     * param[in] : reqType : Type of diagnostic request
     * param[out] : diagnosticRsp : DIagnostic response in JSON.
     */
    virtual void performTCUDiagnostics(SelfDiagnosticManager::DiagnosticReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, std::string &_diagnosticRsp, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> performTCUDiagnosticsAsync(const SelfDiagnosticManager::DiagnosticReqType &_reqType, PerformTCUDiagnosticsAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to clear TCU DTC.
     * param[in] : dtcCode : DTC to clear
     * param[out] : status : Status of the request
     */
    virtual void clearDTC(uint32_t _dtcCode, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::ClearReqStatus &_status, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> clearDTCAsync(const uint32_t &_dtcCode, ClearDTCAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to read the DID information.
     * param[in] : dataIdentifier : Requested DID
     * param[out] : didInfo : Strcut holding value associated with DID & status.
     */
    virtual void readDID(uint32_t _dataIdentifier, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::DIDReadResult &_didInfo, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> readDIDAsync(const uint32_t &_dataIdentifier, ReadDIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to write the DID information.
     * param[in] : didWriteInfo : DID info to be written
     * param[out] : status : Status of the request
     */
    virtual void writeDID(SelfDiagnosticManager::DIDWriteReq _didWriteInfo, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::WriteDIDReqStatus &_status, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> writeDIDAsync(const SelfDiagnosticManager::DIDWriteReq &_didWriteInfo, WriteDIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_PROXY_BASE_HPP_
