/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Self Diagnostic Manager Interface
 * brief : This interface provides API for client to initiate a diagnostic request.
 */
#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_STUB_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/toscore/sdmservice/SelfDiagnosticManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SelfDiagnosticManager. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SelfDiagnosticManagerStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SelfDiagnosticManager {
 public:


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SelfDiagnosticManager.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SelfDiagnosticManagerStubRemoteEvent
{
public:
    virtual ~SelfDiagnosticManagerStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SelfDiagnosticManager to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SelfDiagnosticManagerStub
    : public virtual CommonAPI::Stub<SelfDiagnosticManagerStubAdapter, SelfDiagnosticManagerStubRemoteEvent>
{
public:
    typedef std::function<void (SelfDiagnosticManager::SetReqStatus _status)> setCustomPlatformDTCReply_t;
    typedef std::function<void (std::string _diagnosticRsp)> performTCUDiagnosticsReply_t;
    typedef std::function<void (SelfDiagnosticManager::ClearReqStatus _status)> clearDTCReply_t;
    typedef std::function<void (SelfDiagnosticManager::DIDReadResult _didInfo)> readDIDReply_t;
    typedef std::function<void (SelfDiagnosticManager::WriteDIDReqStatus _status)> writeDIDReply_t;

    virtual ~SelfDiagnosticManagerStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 5);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * brief : Interface to set custom DTC to platform
     * param[in] : customDTCReq : Custom DTC Information
     * param[out] : status : Status of the request
     */
    /// This is the method that will be called on remote calls on the method setCustomPlatformDTC.
    virtual void setCustomPlatformDTC(const std::shared_ptr<CommonAPI::ClientId> _client, SelfDiagnosticManager::DTCSetReq _customDTCReq, setCustomPlatformDTCReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
     * param[in] : reqType : Type of diagnostic request
     * param[out] : diagnosticRsp : DIagnostic response in JSON.
     */
    /// This is the method that will be called on remote calls on the method performTCUDiagnostics.
    virtual void performTCUDiagnostics(const std::shared_ptr<CommonAPI::ClientId> _client, SelfDiagnosticManager::DiagnosticReqType _reqType, performTCUDiagnosticsReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to clear TCU DTC.
     * param[in] : dtcCode : DTC to clear
     * param[out] : status : Status of the request
     */
    /// This is the method that will be called on remote calls on the method clearDTC.
    virtual void clearDTC(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _dtcCode, clearDTCReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to read the DID information.
     * param[in] : dataIdentifier : Requested DID
     * param[out] : didInfo : Strcut holding value associated with DID & status.
     */
    /// This is the method that will be called on remote calls on the method readDID.
    virtual void readDID(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _dataIdentifier, readDIDReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to write the DID information.
     * param[in] : didWriteInfo : DID info to be written
     * param[out] : status : Status of the request
     */
    /// This is the method that will be called on remote calls on the method writeDID.
    virtual void writeDID(const std::shared_ptr<CommonAPI::ClientId> _client, SelfDiagnosticManager::DIDWriteReq _didWriteInfo, writeDIDReply_t _reply) = 0;


    using CommonAPI::Stub<SelfDiagnosticManagerStubAdapter, SelfDiagnosticManagerStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SelfDiagnosticManagerStubAdapter, SelfDiagnosticManagerStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SelfDiagnosticManagerStubAdapter, SelfDiagnosticManagerStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SelfDiagnosticManagerStubRemoteEvent RemoteEventType;
    typedef SelfDiagnosticManager StubInterface;
};

} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_STUB_HPP_
