/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Self Diagnostic Manager Interface
 * brief : This interface provides API for client to initiate a diagnostic request.
 */
#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/toscore/sdmservice/SelfDiagnosticManagerStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {

/**
 * Provides a default implementation for SelfDiagnosticManagerStubRemoteEvent and
 * SelfDiagnosticManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SelfDiagnosticManagerStubDefault
    : public virtual SelfDiagnosticManagerStub {
public:
    COMMONAPI_EXPORT SelfDiagnosticManagerStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SelfDiagnosticManager::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SelfDiagnosticManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr< SelfDiagnosticManagerStubAdapter> &_adapter) {
        CommonAPI::Stub<SelfDiagnosticManagerStubAdapter, SelfDiagnosticManagerStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * brief : Interface to set custom DTC to platform
     * param[in] : customDTCReq : Custom DTC Information
     * param[out] : status : Status of the request
     */
    COMMONAPI_EXPORT virtual void setCustomPlatformDTC(const std::shared_ptr<CommonAPI::ClientId> _client, SelfDiagnosticManager::DTCSetReq _customDTCReq, setCustomPlatformDTCReply_t _reply) {
        (void)_client;
        (void)_customDTCReq;
        SelfDiagnosticManager::SetReqStatus status = SelfDiagnosticManager::SetReqStatus::SDM_ERR_SUCCESS;
        if (!status.validate()) {
            return;
        }
        _reply(status);
    }
    /*
     * description: 
     * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
     * param[in] : reqType : Type of diagnostic request
     * param[out] : diagnosticRsp : DIagnostic response in JSON.
     */
    COMMONAPI_EXPORT virtual void performTCUDiagnostics(const std::shared_ptr<CommonAPI::ClientId> _client, SelfDiagnosticManager::DiagnosticReqType _reqType, performTCUDiagnosticsReply_t _reply) {
        (void)_client;
        (void)_reqType;
        std::string diagnosticRsp = "";
        _reply(diagnosticRsp);
    }
    /*
     * description: 
     * brief : Interface to clear TCU DTC.
     * param[in] : dtcCode : DTC to clear
     * param[out] : status : Status of the request
     */
    COMMONAPI_EXPORT virtual void clearDTC(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _dtcCode, clearDTCReply_t _reply) {
        (void)_client;
        (void)_dtcCode;
        SelfDiagnosticManager::ClearReqStatus status = SelfDiagnosticManager::ClearReqStatus::SDM_ERR_SUCCESS;
        if (!status.validate()) {
            return;
        }
        _reply(status);
    }
    /*
     * description: 
     * brief : Interface to read the DID information.
     * param[in] : dataIdentifier : Requested DID
     * param[out] : didInfo : Strcut holding value associated with DID & status.
     */
    COMMONAPI_EXPORT virtual void readDID(const std::shared_ptr<CommonAPI::ClientId> _client, uint32_t _dataIdentifier, readDIDReply_t _reply) {
        (void)_client;
        (void)_dataIdentifier;
        SelfDiagnosticManager::DIDReadResult didInfo = {};
        _reply(didInfo);
    }
    /*
     * description: 
     * brief : Interface to write the DID information.
     * param[in] : didWriteInfo : DID info to be written
     * param[out] : status : Status of the request
     */
    COMMONAPI_EXPORT virtual void writeDID(const std::shared_ptr<CommonAPI::ClientId> _client, SelfDiagnosticManager::DIDWriteReq _didWriteInfo, writeDIDReply_t _reply) {
        (void)_client;
        (void)_didWriteInfo;
        SelfDiagnosticManager::WriteDIDReqStatus status = SelfDiagnosticManager::WriteDIDReqStatus::SDM_ERR_SUCCESS;
        if (!status.validate()) {
            return;
        }
        _reply(status);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SelfDiagnosticManagerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SelfDiagnosticManagerStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SelfDiagnosticManagerStubDefault *defaultStub_;
    };
protected:
    SelfDiagnosticManagerStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_STUB_DEFAULT
