/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Self Diagnostic Manager Interface
 * brief : This interface provides API for client to initiate a diagnostic request.
 */
#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_SELF_DIAGNOSTIC_MANAGER_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_SELF_DIAGNOSTIC_MANAGER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {

class SelfDiagnosticManager {
public:
    virtual ~SelfDiagnosticManager() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    /*
     * description: 
     * brief : Structure holding the custom DTC information
     */
    struct DTCSetReq : CommonAPI::Struct< uint32_t, uint8_t, std::string> {
    
        DTCSetReq()
        {
            std::get< 0>(values_) = 0ul;
            std::get< 1>(values_) = 0u;
            std::get< 2>(values_) = "";
        }
        DTCSetReq(const uint32_t &_dtcCode, const uint8_t &_compID, const std::string &_errorDesc)
        {
            std::get< 0>(values_) = _dtcCode;
            std::get< 1>(values_) = _compID;
            std::get< 2>(values_) = _errorDesc;
        }
        inline const uint32_t &getDtcCode() const { return std::get< 0>(values_); }
        inline void setDtcCode(const uint32_t &_value) { std::get< 0>(values_) = _value; }
        inline const uint8_t &getCompID() const { return std::get< 1>(values_); }
        inline void setCompID(const uint8_t &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getErrorDesc() const { return std::get< 2>(values_); }
        inline void setErrorDesc(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline bool operator==(const DTCSetReq& _other) const {
        return (getDtcCode() == _other.getDtcCode() && getCompID() == _other.getCompID() && getErrorDesc() == _other.getErrorDesc());
        }
        inline bool operator!=(const DTCSetReq &_other) const {
            return !((*this) == _other);
        }
    
    };
    
    struct ReadDIDReqStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SDM_ERR_SUCCESS = 0,
            SDM_ERR_FAILURE = 1,
            SDM_ERR_READ_DID = 2,
            SDM_ERR_ENTER_DEFAULT_SESSION = 3
        };
    
        ReadDIDReqStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS)) {}
        ReadDIDReqStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS):
                case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE):
                case static_cast< uint8_t>(Literal::SDM_ERR_READ_DID):
                case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_DEFAULT_SESSION):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const ReadDIDReqStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const ReadDIDReqStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const ReadDIDReqStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const ReadDIDReqStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const ReadDIDReqStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const ReadDIDReqStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS): return "SDM_ERR_SUCCESS";
            case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE): return "SDM_ERR_FAILURE";
            case static_cast< uint8_t>(Literal::SDM_ERR_READ_DID): return "SDM_ERR_READ_DID";
            case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_DEFAULT_SESSION): return "SDM_ERR_ENTER_DEFAULT_SESSION";
            default: return "UNDEFINED";
            }
        }
    };
    /*
     * description: 
     * brief : Structure holding the DID read output
     */
    struct DIDReadResult : CommonAPI::Struct< std::string, ReadDIDReqStatus> {
    
        DIDReadResult()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = ReadDIDReqStatus();
        }
        DIDReadResult(const std::string &_didValue, const ReadDIDReqStatus &_status)
        {
            std::get< 0>(values_) = _didValue;
            std::get< 1>(values_) = _status;
        }
        inline const std::string &getDidValue() const { return std::get< 0>(values_); }
        inline void setDidValue(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const ReadDIDReqStatus &getStatus() const { return std::get< 1>(values_); }
        inline void setStatus(const ReadDIDReqStatus &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const DIDReadResult& _other) const {
        return (getDidValue() == _other.getDidValue() && getStatus() == _other.getStatus());
        }
        inline bool operator!=(const DIDReadResult &_other) const {
            return !((*this) == _other);
        }
    
    };
    /*
     * description: 
     * brief : Structure holding the DID write input
     */
    struct DIDWriteReq : CommonAPI::Struct< uint32_t, std::string> {
    
        DIDWriteReq()
        {
            std::get< 0>(values_) = 0ul;
            std::get< 1>(values_) = "";
        }
        DIDWriteReq(const uint32_t &_dataIdentifier, const std::string &_didValue)
        {
            std::get< 0>(values_) = _dataIdentifier;
            std::get< 1>(values_) = _didValue;
        }
        inline const uint32_t &getDataIdentifier() const { return std::get< 0>(values_); }
        inline void setDataIdentifier(const uint32_t &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getDidValue() const { return std::get< 1>(values_); }
        inline void setDidValue(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const DIDWriteReq& _other) const {
        return (getDataIdentifier() == _other.getDataIdentifier() && getDidValue() == _other.getDidValue());
        }
        inline bool operator!=(const DIDWriteReq &_other) const {
            return !((*this) == _other);
        }
    
    };
    
    struct SetReqStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SDM_ERR_SUCCESS = 0,
            SDM_ERR_FAILURE = 1,
            SDM_ERR_COMMONAPI_FAILURE = 2
        };
    
        SetReqStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS)) {}
        SetReqStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS):
                case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE):
                case static_cast< uint8_t>(Literal::SDM_ERR_COMMONAPI_FAILURE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const SetReqStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const SetReqStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const SetReqStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const SetReqStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const SetReqStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const SetReqStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS): return "SDM_ERR_SUCCESS";
            case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE): return "SDM_ERR_FAILURE";
            case static_cast< uint8_t>(Literal::SDM_ERR_COMMONAPI_FAILURE): return "SDM_ERR_COMMONAPI_FAILURE";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct DiagnosticReqType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            GET_ALL_TCU_DTC_INFO = 0,
            GET_TCU_HEALTH_INFO = 1,
            GET_ALL_TCU_COMPONENT_ERROR = 2,
            GET_ACTIVE_TCU_COMPONENT_ERROR = 3,
            CLEAR_ALL_TCU_DTC = 4,
            GET_TCU_HEALTH_INFO_AND_HEAL = 5,
            RESERVED_CMD_FOR_FUTURE_USE_2 = 6,
            RESERVED_CMD_FOR_FUTURE_USE_3 = 7,
            RESERVED_CMD_FOR_FUTURE_USE_4 = 8,
            RESERVED_CMD_FOR_FUTURE_USE_5 = 9,
            RESERVED_CMD_FOR_FUTURE_USE_6 = 10
        };
    
        DiagnosticReqType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::GET_ALL_TCU_DTC_INFO)) {}
        DiagnosticReqType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::GET_ALL_TCU_DTC_INFO):
                case static_cast< uint8_t>(Literal::GET_TCU_HEALTH_INFO):
                case static_cast< uint8_t>(Literal::GET_ALL_TCU_COMPONENT_ERROR):
                case static_cast< uint8_t>(Literal::GET_ACTIVE_TCU_COMPONENT_ERROR):
                case static_cast< uint8_t>(Literal::CLEAR_ALL_TCU_DTC):
                case static_cast< uint8_t>(Literal::GET_TCU_HEALTH_INFO_AND_HEAL):
                case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_2):
                case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_3):
                case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_4):
                case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_5):
                case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_6):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const DiagnosticReqType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const DiagnosticReqType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const DiagnosticReqType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const DiagnosticReqType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const DiagnosticReqType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const DiagnosticReqType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::GET_ALL_TCU_DTC_INFO): return "GET_ALL_TCU_DTC_INFO";
            case static_cast< uint8_t>(Literal::GET_TCU_HEALTH_INFO): return "GET_TCU_HEALTH_INFO";
            case static_cast< uint8_t>(Literal::GET_ALL_TCU_COMPONENT_ERROR): return "GET_ALL_TCU_COMPONENT_ERROR";
            case static_cast< uint8_t>(Literal::GET_ACTIVE_TCU_COMPONENT_ERROR): return "GET_ACTIVE_TCU_COMPONENT_ERROR";
            case static_cast< uint8_t>(Literal::CLEAR_ALL_TCU_DTC): return "CLEAR_ALL_TCU_DTC";
            case static_cast< uint8_t>(Literal::GET_TCU_HEALTH_INFO_AND_HEAL): return "GET_TCU_HEALTH_INFO_AND_HEAL";
            case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_2): return "RESERVED_CMD_FOR_FUTURE_USE_2";
            case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_3): return "RESERVED_CMD_FOR_FUTURE_USE_3";
            case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_4): return "RESERVED_CMD_FOR_FUTURE_USE_4";
            case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_5): return "RESERVED_CMD_FOR_FUTURE_USE_5";
            case static_cast< uint8_t>(Literal::RESERVED_CMD_FOR_FUTURE_USE_6): return "RESERVED_CMD_FOR_FUTURE_USE_6";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct ClearReqStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SDM_ERR_SUCCESS = 0,
            SDM_ERR_FAILURE = 1,
            SDM_ERR_COMMONAPI_FAILURE = 2
        };
    
        ClearReqStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS)) {}
        ClearReqStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS):
                case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE):
                case static_cast< uint8_t>(Literal::SDM_ERR_COMMONAPI_FAILURE):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const ClearReqStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const ClearReqStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const ClearReqStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const ClearReqStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const ClearReqStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const ClearReqStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS): return "SDM_ERR_SUCCESS";
            case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE): return "SDM_ERR_FAILURE";
            case static_cast< uint8_t>(Literal::SDM_ERR_COMMONAPI_FAILURE): return "SDM_ERR_COMMONAPI_FAILURE";
            default: return "UNDEFINED";
            }
        }
    };
    
    struct WriteDIDReqStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            SDM_ERR_SUCCESS = 0,
            SDM_ERR_FAILURE = 1,
            SDM_ERR_ENTER_DEFAULT_SESSION = 2,
            SDM_ERR_ENTER_EXTD_DIAG_SESSION = 3,
            SDM_ERR_ENTER_PROGRAMMING_SESSION = 4,
            SDM_ERR_UNLOCK_ECU = 5,
            SDM_ERR_WRITE_DID = 6
        };
    
        WriteDIDReqStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS)) {}
        WriteDIDReqStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS):
                case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE):
                case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_DEFAULT_SESSION):
                case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_EXTD_DIAG_SESSION):
                case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_PROGRAMMING_SESSION):
                case static_cast< uint8_t>(Literal::SDM_ERR_UNLOCK_ECU):
                case static_cast< uint8_t>(Literal::SDM_ERR_WRITE_DID):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const WriteDIDReqStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const WriteDIDReqStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const WriteDIDReqStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const WriteDIDReqStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const WriteDIDReqStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const WriteDIDReqStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::SDM_ERR_SUCCESS): return "SDM_ERR_SUCCESS";
            case static_cast< uint8_t>(Literal::SDM_ERR_FAILURE): return "SDM_ERR_FAILURE";
            case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_DEFAULT_SESSION): return "SDM_ERR_ENTER_DEFAULT_SESSION";
            case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_EXTD_DIAG_SESSION): return "SDM_ERR_ENTER_EXTD_DIAG_SESSION";
            case static_cast< uint8_t>(Literal::SDM_ERR_ENTER_PROGRAMMING_SESSION): return "SDM_ERR_ENTER_PROGRAMMING_SESSION";
            case static_cast< uint8_t>(Literal::SDM_ERR_UNLOCK_ECU): return "SDM_ERR_UNLOCK_ECU";
            case static_cast< uint8_t>(Literal::SDM_ERR_WRITE_DID): return "SDM_ERR_WRITE_DID";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* SelfDiagnosticManager::getInterface() {
    return ("commonapi.toscore.sdmservice.SelfDiagnosticManager:v1_0");
}

CommonAPI::Version SelfDiagnosticManager::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}

/*
 * description: 
 * brief : Structure holding the custom DTC information
 */
/*
 * description: 
 * brief : Structure holding the DID read output
 */
/*
 * description: 
 * brief : Structure holding the DID write input
 */
/*
 * description: 
 * brief : Enumeration indicating the status of custom DTC request
 */
/*
 * description: 
 * brief : Enumeration indicating the type of diagnostic request
 */
/*
 * description: 
 * brief : Enumeration indicating the status of clear DTC request.
 */
/*
 * description: 
 * brief : Enumeration indicating the status of read DID request
 */
/*
 * description: 
 * brief : Enumeration indicating the status of write DID request
 */

} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_SELF_DIAGNOSTIC_MANAGER_HPP_
