/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : Self Diagnostic Manager Interface
 * brief : This interface provides API for client to initiate a diagnostic request.
 */
#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_SELF_DIAGNOSTIC_MANAGER_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_SELF_DIAGNOSTIC_MANAGER_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/toscore/sdmservice/SelfDiagnosticManagerStub.hpp>
#include <v1/commonapi/toscore/sdmservice/SelfDiagnosticManagerSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {

template <typename _Stub = ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub, typename... _Stubs>
class SelfDiagnosticManagerSomeIPStubAdapterInternal
    : public virtual SelfDiagnosticManagerStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SelfDiagnosticManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SelfDiagnosticManagerSomeIPStubAdapterHelper;

    ~SelfDiagnosticManagerSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SelfDiagnosticManagerSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub,
        CommonAPI::Version
    > getSelfDiagnosticManagerInterfaceVersionStubDispatcher;

    /*
     * description: 
     * brief : Interface to set custom DTC to platform
     * param[in] : customDTCReq : Custom DTC Information
     * param[out] : status : Status of the request
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub,
        std::tuple< SelfDiagnosticManager::DTCSetReq>,
        std::tuple< SelfDiagnosticManager::SetReqStatus>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DTCSetReqDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::SetReqStatusDeployment_t>
    > setCustomPlatformDTCStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
     * param[in] : reqType : Type of diagnostic request
     * param[out] : diagnosticRsp : DIagnostic response in JSON.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub,
        std::tuple< SelfDiagnosticManager::DiagnosticReqType>,
        std::tuple< std::string>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DiagnosticReqTypeDeployment_t>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > performTCUDiagnosticsStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to clear TCU DTC.
     * param[in] : dtcCode : DTC to clear
     * param[out] : status : Status of the request
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub,
        std::tuple< uint32_t>,
        std::tuple< SelfDiagnosticManager::ClearReqStatus>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::ClearReqStatusDeployment_t>
    > clearDTCStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to read the DID information.
     * param[in] : dataIdentifier : Requested DID
     * param[out] : didInfo : Strcut holding value associated with DID & status.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub,
        std::tuple< uint32_t>,
        std::tuple< SelfDiagnosticManager::DIDReadResult>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint32_t>>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DIDReadResultDeployment_t>
    > readDIDStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to write the DID information.
     * param[in] : didWriteInfo : DID info to be written
     * param[out] : status : Status of the request
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub,
        std::tuple< SelfDiagnosticManager::DIDWriteReq>,
        std::tuple< SelfDiagnosticManager::WriteDIDReqStatus>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DIDWriteReqDeployment_t>,
        std::tuple< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::WriteDIDReqStatusDeployment_t>
    > writeDIDStubDispatcher;
    
    SelfDiagnosticManagerSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SelfDiagnosticManagerSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SelfDiagnosticManagerStub>(_stub)),
        getSelfDiagnosticManagerInterfaceVersionStubDispatcher(&SelfDiagnosticManagerStub::lockInterfaceVersionAttribute, &SelfDiagnosticManagerStub::getInterfaceVersion, false, true),
        setCustomPlatformDTCStubDispatcher(
            &SelfDiagnosticManagerStub::setCustomPlatformDTC,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DTCSetReqDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::SetReqStatusDeployment_t* >(nullptr)))
        
        ,
        performTCUDiagnosticsStubDispatcher(
            &SelfDiagnosticManagerStub::performTCUDiagnostics,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DiagnosticReqTypeDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        clearDTCStubDispatcher(
            &SelfDiagnosticManagerStub::clearDTC,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::ClearReqStatusDeployment_t* >(nullptr)))
        
        ,
        readDIDStubDispatcher(
            &SelfDiagnosticManagerStub::readDID,
            false,
            _stub->hasElement(3),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint32_t>* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DIDReadResultDeployment_t* >(nullptr)))
        
        ,
        writeDIDStubDispatcher(
            &SelfDiagnosticManagerStub::writeDID,
            false,
            _stub->hasElement(4),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::DIDWriteReqDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::WriteDIDReqStatusDeployment_t* >(nullptr)))
        
    {
        /*
         * description: 
         * brief : Interface to set custom DTC to platform
         * param[in] : customDTCReq : Custom DTC Information
         * param[out] : status : Status of the request
         */
        SelfDiagnosticManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2711) }, &setCustomPlatformDTCStubDispatcher );
        /*
         * description: 
         * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
         * param[in] : reqType : Type of diagnostic request
         * param[out] : diagnosticRsp : DIagnostic response in JSON.
         */
        SelfDiagnosticManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2712) }, &performTCUDiagnosticsStubDispatcher );
        /*
         * description: 
         * brief : Interface to clear TCU DTC.
         * param[in] : dtcCode : DTC to clear
         * param[out] : status : Status of the request
         */
        SelfDiagnosticManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2713) }, &clearDTCStubDispatcher );
        /*
         * description: 
         * brief : Interface to read the DID information.
         * param[in] : dataIdentifier : Requested DID
         * param[out] : didInfo : Strcut holding value associated with DID & status.
         */
        SelfDiagnosticManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2714) }, &readDIDStubDispatcher );
        /*
         * description: 
         * brief : Interface to write the DID information.
         * param[in] : didWriteInfo : DID info to be written
         * param[out] : status : Status of the request
         */
        SelfDiagnosticManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2715) }, &writeDIDStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void SelfDiagnosticManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SelfDiagnosticManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManagerStub, typename... _Stubs>
class SelfDiagnosticManagerSomeIPStubAdapter
    : public SelfDiagnosticManagerSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SelfDiagnosticManagerSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SelfDiagnosticManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_SOMEIP_STUB_ADAPTER_HPP_
