/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Self Diagnostic Manager Interface
 * brief : This interface provides API for client to initiate a diagnostic request.
 */
#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_PROXY_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_PROXY_HPP_

#include <v1/commonapi/toscore/sdmservice/SelfDiagnosticManagerProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {

template <typename ... _AttributeExtensions>
class SelfDiagnosticManagerProxy
    : virtual public SelfDiagnosticManager,
      virtual public SelfDiagnosticManagerProxyBase,
      virtual public _AttributeExtensions... {
public:
    SelfDiagnosticManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SelfDiagnosticManagerProxy();

    typedef SelfDiagnosticManager InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * brief : Interface to set custom DTC to platform
     * param[in] : customDTCReq : Custom DTC Information
     * param[out] : status : Status of the request
     * Calls setCustomPlatformDTC with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void setCustomPlatformDTC(SelfDiagnosticManager::DTCSetReq _customDTCReq, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::SetReqStatus &_status, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls setCustomPlatformDTC with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> setCustomPlatformDTCAsync(const SelfDiagnosticManager::DTCSetReq &_customDTCReq, SetCustomPlatformDTCAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
     * param[in] : reqType : Type of diagnostic request
     * param[out] : diagnosticRsp : DIagnostic response in JSON.
     * Calls performTCUDiagnostics with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void performTCUDiagnostics(SelfDiagnosticManager::DiagnosticReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, std::string &_diagnosticRsp, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls performTCUDiagnostics with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> performTCUDiagnosticsAsync(const SelfDiagnosticManager::DiagnosticReqType &_reqType, PerformTCUDiagnosticsAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to clear TCU DTC.
     * param[in] : dtcCode : DTC to clear
     * param[out] : status : Status of the request
     * Calls clearDTC with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void clearDTC(uint32_t _dtcCode, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::ClearReqStatus &_status, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls clearDTC with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> clearDTCAsync(const uint32_t &_dtcCode, ClearDTCAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to read the DID information.
     * param[in] : dataIdentifier : Requested DID
     * param[out] : didInfo : Strcut holding value associated with DID & status.
     * Calls readDID with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void readDID(uint32_t _dataIdentifier, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::DIDReadResult &_didInfo, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls readDID with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> readDIDAsync(const uint32_t &_dataIdentifier, ReadDIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to write the DID information.
     * param[in] : didWriteInfo : DID info to be written
     * param[out] : status : Status of the request
     * Calls writeDID with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void writeDID(SelfDiagnosticManager::DIDWriteReq _didWriteInfo, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::WriteDIDReqStatus &_status, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls writeDID with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> writeDIDAsync(const SelfDiagnosticManager::DIDWriteReq &_didWriteInfo, WriteDIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< SelfDiagnosticManagerProxyBase> delegate_;
};

typedef SelfDiagnosticManagerProxy<> SelfDiagnosticManagerProxyDefault;


//
// SelfDiagnosticManagerProxy Implementation
//
template <typename ... _AttributeExtensions>
SelfDiagnosticManagerProxy<_AttributeExtensions...>::SelfDiagnosticManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SelfDiagnosticManagerProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SelfDiagnosticManagerProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SelfDiagnosticManagerProxy<_AttributeExtensions...>::~SelfDiagnosticManagerProxy() {
}

/*
 * description: 
 * brief : Interface to set custom DTC to platform
 * param[in] : customDTCReq : Custom DTC Information
 * param[out] : status : Status of the request
 */
template <typename ... _AttributeExtensions>
void SelfDiagnosticManagerProxy<_AttributeExtensions...>::setCustomPlatformDTC(SelfDiagnosticManager::DTCSetReq _customDTCReq, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::SetReqStatus &_status, const CommonAPI::CallInfo *_info) {
    delegate_->setCustomPlatformDTC(_customDTCReq, _internalCallStatus, _status, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SelfDiagnosticManagerProxy<_AttributeExtensions...>::setCustomPlatformDTCAsync(const SelfDiagnosticManager::DTCSetReq &_customDTCReq, SetCustomPlatformDTCAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->setCustomPlatformDTCAsync(_customDTCReq, _callback, _info);
}
/*
 * description: 
 * brief : Interface to perform TCU diagnostics and T.OS health check for non-UDS communication.
 * param[in] : reqType : Type of diagnostic request
 * param[out] : diagnosticRsp : DIagnostic response in JSON.
 */
template <typename ... _AttributeExtensions>
void SelfDiagnosticManagerProxy<_AttributeExtensions...>::performTCUDiagnostics(SelfDiagnosticManager::DiagnosticReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, std::string &_diagnosticRsp, const CommonAPI::CallInfo *_info) {
    if (!_reqType.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->performTCUDiagnostics(_reqType, _internalCallStatus, _diagnosticRsp, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SelfDiagnosticManagerProxy<_AttributeExtensions...>::performTCUDiagnosticsAsync(const SelfDiagnosticManager::DiagnosticReqType &_reqType, PerformTCUDiagnosticsAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_reqType.validate()) {
        std::string diagnosticRsp = "";
        _callback(CommonAPI::CallStatus::INVALID_VALUE, diagnosticRsp);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->performTCUDiagnosticsAsync(_reqType, _callback, _info);
}
/*
 * description: 
 * brief : Interface to clear TCU DTC.
 * param[in] : dtcCode : DTC to clear
 * param[out] : status : Status of the request
 */
template <typename ... _AttributeExtensions>
void SelfDiagnosticManagerProxy<_AttributeExtensions...>::clearDTC(uint32_t _dtcCode, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::ClearReqStatus &_status, const CommonAPI::CallInfo *_info) {
    delegate_->clearDTC(_dtcCode, _internalCallStatus, _status, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SelfDiagnosticManagerProxy<_AttributeExtensions...>::clearDTCAsync(const uint32_t &_dtcCode, ClearDTCAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->clearDTCAsync(_dtcCode, _callback, _info);
}
/*
 * description: 
 * brief : Interface to read the DID information.
 * param[in] : dataIdentifier : Requested DID
 * param[out] : didInfo : Strcut holding value associated with DID & status.
 */
template <typename ... _AttributeExtensions>
void SelfDiagnosticManagerProxy<_AttributeExtensions...>::readDID(uint32_t _dataIdentifier, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::DIDReadResult &_didInfo, const CommonAPI::CallInfo *_info) {
    delegate_->readDID(_dataIdentifier, _internalCallStatus, _didInfo, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SelfDiagnosticManagerProxy<_AttributeExtensions...>::readDIDAsync(const uint32_t &_dataIdentifier, ReadDIDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->readDIDAsync(_dataIdentifier, _callback, _info);
}
/*
 * description: 
 * brief : Interface to write the DID information.
 * param[in] : didWriteInfo : DID info to be written
 * param[out] : status : Status of the request
 */
template <typename ... _AttributeExtensions>
void SelfDiagnosticManagerProxy<_AttributeExtensions...>::writeDID(SelfDiagnosticManager::DIDWriteReq _didWriteInfo, CommonAPI::CallStatus &_internalCallStatus, SelfDiagnosticManager::WriteDIDReqStatus &_status, const CommonAPI::CallInfo *_info) {
    delegate_->writeDID(_didWriteInfo, _internalCallStatus, _status, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SelfDiagnosticManagerProxy<_AttributeExtensions...>::writeDIDAsync(const SelfDiagnosticManager::DIDWriteReq &_didWriteInfo, WriteDIDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->writeDIDAsync(_didWriteInfo, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SelfDiagnosticManagerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SelfDiagnosticManagerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SelfDiagnosticManagerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SelfDiagnosticManagerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SelfDiagnosticManagerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SelfDiagnosticManagerProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_PROXY_HPP_
