/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */

#ifndef V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_SOMEIP_DEPLOYMENT_HPP_
#define V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_SOMEIP_DEPLOYMENT_HPP_


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif
#include <CommonAPI/SomeIP/Deployment.hpp>
#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace sdmservice {
namespace SelfDiagnosticManager_ {

// Interface-specific deployment types
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> SetReqStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> DiagnosticReqTypeDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ClearReqStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> ReadDIDReqStatusDeployment_t;
typedef CommonAPI::SomeIP::EnumerationDeployment<uint8_t> WriteDIDReqStatusDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::IntegerDeployment<uint8_t>,
    CommonAPI::SomeIP::StringDeployment
> DTCSetReqDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::StringDeployment,
    ::v1::commonapi::toscore::sdmservice::SelfDiagnosticManager_::ReadDIDReqStatusDeployment_t
> DIDReadResultDeployment_t;
typedef CommonAPI::SomeIP::StructDeployment<
    CommonAPI::SomeIP::IntegerDeployment<uint32_t>,
    CommonAPI::SomeIP::StringDeployment
> DIDWriteReqDeployment_t;

// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployment

// Broadcast-specific deployments

} // namespace SelfDiagnosticManager_
} // namespace sdmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TOSCORE_SDMSERVICE_Self_Diagnostic_Manager_SOMEIP_DEPLOYMENT_HPP_
