/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_STUB_DEFAULT_HPP_
#define V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v1/commonapi/toscore/cmservice/ContainerManagerStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

/**
 * Provides a default implementation for ContainerManagerStubRemoteEvent and
 * ContainerManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT ContainerManagerStubDefault
    : public virtual ContainerManagerStub {
public:
    COMMONAPI_EXPORT ContainerManagerStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(ContainerManager::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT ContainerManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr< ContainerManagerStubAdapter> &_adapter) {
        CommonAPI::Stub<ContainerManagerStubAdapter, ContainerManagerStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    COMMONAPI_EXPORT virtual void getVersion(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getVersionReply_t _reply) {
        (void)_client;
        (void)_request;
        std::string compVersion = "";
        _reply(compVersion);
    }
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : ComponentID : Component identification number
     */
    COMMONAPI_EXPORT virtual void getComponentID(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getComponentIDReply_t _reply) {
        (void)_client;
        (void)_request;
        uint8_t componentID = 0u;
        _reply(componentID);
    }
    /*
     * description: 
     * brief : Interface to get the version of container
     * param[in] : request : Dummy boolean value
     * param[out] : containerVersionReport : JSON object with container version information
     */
    COMMONAPI_EXPORT virtual void getContainerVersion(const std::shared_ptr<CommonAPI::ClientId> _client, bool _request, getContainerVersionReply_t _reply) {
        (void)_client;
        (void)_request;
        std::string containerVersionReport = "";
        _reply(containerVersionReport);
    }
    /*
     * description: 
     * brief : Interface to perform Container Action
     * param[in] : contAction : Contains container ID, action type
     * param[out] : status : Response getting after performing container action
     */
    COMMONAPI_EXPORT virtual void performContainerAction(const std::shared_ptr<CommonAPI::ClientId> _client, ContainerManager::DataIn _contAction, performContainerActionReply_t _reply) {
        (void)_client;
        (void)_contAction;
        std::string status = "";
        _reply(status);
    }
    /*
     * description: 
     * brief : Interface to perform Container App Action
     * param[in] : appAction : Contains container ID, application Name and action type
     * param[out] : status : Response getting after performing container app action
     */
    COMMONAPI_EXPORT virtual void performAppAction(const std::shared_ptr<CommonAPI::ClientId> _client, ContainerManager::DataIn _appAction, performAppActionReply_t _reply) {
        (void)_client;
        (void)_appAction;
        std::string status = "";
        _reply(status);
    }
    /*
     * description: 
     * brief : Interface to perform Container Update
     * param[in] : containerPackage : JSON object containing the details of container to be updated
     * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
     */
    COMMONAPI_EXPORT virtual void performContainerUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _containerPackage, performContainerUpdateReply_t _reply) {
        (void)_client;
        (void)_containerPackage;
        std::string containerUpdateStatusReport = "";
        _reply(containerUpdateStatusReport);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual ContainerManagerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(ContainerManagerStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        ContainerManagerStubDefault *defaultStub_;
    };
protected:
    ContainerManagerStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_STUB_DEFAULT
