/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#include <v1/commonapi/toscore/cmservice/ContainerManagerSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createContainerManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< ContainerManagerSomeIPProxy>(_address, _connection);
}

void initializeContainerManagerSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.toscore.cmservice.ContainerManager:v1_0:commonapi.toscore.cmservice.ContainerManager",
        0xfaf, 0x7df, 1, 0);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.toscore.cmservice.ContainerManager:v1_0",
        &createContainerManagerSomeIPProxy);
}

INITIALIZER(registerContainerManagerSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeContainerManagerSomeIPProxy);
}

ContainerManagerSomeIPProxy::ContainerManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection)
{
}

ContainerManagerSomeIPProxy::~ContainerManagerSomeIPProxy() {
    completed_.set_value();
}



/*
 * description: 
 * brief : Interface to get the component version
 * param[in] : request : Dummy integer value
 * param[out] : compVersion : Version of the component
 */
void ContainerManagerSomeIPProxy::getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_compVersion(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2711),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        _internalCallStatus,
        deploy_compVersion);
    _compVersion = deploy_compVersion.getValue();
}

std::future<CommonAPI::CallStatus> ContainerManagerSomeIPProxy::getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_compVersion(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2711),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _compVersion) {
            if (_callback)
                _callback(_internalCallStatus, _compVersion.getValue());
        },
        std::make_tuple(deploy_compVersion));
}

/*
 * description: 
 * brief : Interface to get the component identification number
 * param[in] : request : Dummy integer value
 * param[out] : ComponentID : Component identification number
 */
void ContainerManagerSomeIPProxy::getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_componentID(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2712),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        _internalCallStatus,
        deploy_componentID);
    _componentID = deploy_componentID.getValue();
}

std::future<CommonAPI::CallStatus> ContainerManagerSomeIPProxy::getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< int32_t, CommonAPI::SomeIP::IntegerDeployment<int32_t>> deploy_request(_request, static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr));
    CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t>> deploy_componentID(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                int32_t,
                CommonAPI::SomeIP::IntegerDeployment<int32_t>
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                uint8_t,
                CommonAPI::SomeIP::IntegerDeployment<uint8_t>
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2712),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint8_t, CommonAPI::SomeIP::IntegerDeployment<uint8_t> > _componentID) {
            if (_callback)
                _callback(_internalCallStatus, _componentID.getValue());
        },
        std::make_tuple(deploy_componentID));
}

/*
 * description: 
 * brief : Interface to get the version of container
 * param[in] : request : Dummy boolean value
 * param[out] : containerVersionReport : JSON object with container version information
 */
void ContainerManagerSomeIPProxy::getContainerVersion(bool _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerVersionReport, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_request(_request, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_containerVersionReport(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2713),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        _internalCallStatus,
        deploy_containerVersionReport);
    _containerVersionReport = deploy_containerVersionReport.getValue();
}

std::future<CommonAPI::CallStatus> ContainerManagerSomeIPProxy::getContainerVersionAsync(const bool &_request, GetContainerVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< bool, CommonAPI::EmptyDeployment> deploy_request(_request, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_containerVersionReport(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                bool,
                CommonAPI::EmptyDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2713),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_request,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _containerVersionReport) {
            if (_callback)
                _callback(_internalCallStatus, _containerVersionReport.getValue());
        },
        std::make_tuple(deploy_containerVersionReport));
}

/*
 * description: 
 * brief : Interface to perform Container Action
 * param[in] : contAction : Contains container ID, action type
 * param[out] : status : Response getting after performing container action
 */
void ContainerManagerSomeIPProxy::performContainerAction(ContainerManager::DataIn _contAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ContainerManager::DataIn, ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t> deploy_contAction(_contAction, static_cast< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_status(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ContainerManager::DataIn,
                ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2714),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_contAction,
        _internalCallStatus,
        deploy_status);
    _status = deploy_status.getValue();
}

std::future<CommonAPI::CallStatus> ContainerManagerSomeIPProxy::performContainerActionAsync(const ContainerManager::DataIn &_contAction, PerformContainerActionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ContainerManager::DataIn, ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t> deploy_contAction(_contAction, static_cast< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_status(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ContainerManager::DataIn,
                ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2714),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_contAction,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _status) {
            if (_callback)
                _callback(_internalCallStatus, _status.getValue());
        },
        std::make_tuple(deploy_status));
}

/*
 * description: 
 * brief : Interface to perform Container App Action
 * param[in] : appAction : Contains container ID, application Name and action type
 * param[out] : status : Response getting after performing container app action
 */
void ContainerManagerSomeIPProxy::performAppAction(ContainerManager::DataIn _appAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ContainerManager::DataIn, ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t> deploy_appAction(_appAction, static_cast< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_status(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ContainerManager::DataIn,
                ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2715),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_appAction,
        _internalCallStatus,
        deploy_status);
    _status = deploy_status.getValue();
}

std::future<CommonAPI::CallStatus> ContainerManagerSomeIPProxy::performAppActionAsync(const ContainerManager::DataIn &_appAction, PerformAppActionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< ContainerManager::DataIn, ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t> deploy_appAction(_appAction, static_cast< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_status(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                ContainerManager::DataIn,
                ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2715),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_appAction,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _status) {
            if (_callback)
                _callback(_internalCallStatus, _status.getValue());
        },
        std::make_tuple(deploy_status));
}

/*
 * description: 
 * brief : Interface to perform Container Update
 * param[in] : containerPackage : JSON object containing the details of container to be updated
 * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
 */
void ContainerManagerSomeIPProxy::performContainerUpdate(std::string _containerPackage, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerUpdateStatusReport, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_containerPackage(_containerPackage, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_containerUpdateStatusReport(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2716),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_containerPackage,
        _internalCallStatus,
        deploy_containerUpdateStatusReport);
    _containerUpdateStatusReport = deploy_containerUpdateStatusReport.getValue();
}

std::future<CommonAPI::CallStatus> ContainerManagerSomeIPProxy::performContainerUpdateAsync(const std::string &_containerPackage, PerformContainerUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_containerPackage(_containerPackage, static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment> deploy_containerUpdateStatusReport(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                std::string,
                CommonAPI::SomeIP::StringDeployment
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2716),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_containerPackage,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::SomeIP::StringDeployment > _containerUpdateStatusReport) {
            if (_callback)
                _callback(_internalCallStatus, _containerUpdateStatusReport.getValue());
        },
        std::make_tuple(deploy_containerUpdateStatusReport));
}

void ContainerManagerSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 1;
    ownVersionMinor = 0;
}

std::future<void> ContainerManagerSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1
