/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSERVICE_CONTAINER_MANAGER_SOMEIP_STUB_ADAPTER_HPP_
#define V1_COMMONAPI_TOSCORE_CMSERVICE_CONTAINER_MANAGER_SOMEIP_STUB_ADAPTER_HPP_

#include <v1/commonapi/toscore/cmservice/ContainerManagerStub.hpp>
#include <v1/commonapi/toscore/cmservice/ContainerManagerSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

template <typename _Stub = ::v1::commonapi::toscore::cmservice::ContainerManagerStub, typename... _Stubs>
class ContainerManagerSomeIPStubAdapterInternal
    : public virtual ContainerManagerStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< ContainerManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> ContainerManagerSomeIPStubAdapterHelper;

    ~ContainerManagerSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        ContainerManagerSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        CommonAPI::Version
    > getContainerManagerInterfaceVersionStubDispatcher;

    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        std::tuple< int32_t>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > getVersionStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : ComponentID : Component identification number
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        std::tuple< int32_t>,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<int32_t>>,
        std::tuple< CommonAPI::SomeIP::IntegerDeployment<uint8_t>>
    > getComponentIDStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to get the version of container
     * param[in] : request : Dummy boolean value
     * param[out] : containerVersionReport : JSON object with container version information
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        std::tuple< bool>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > getContainerVersionStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to perform Container Action
     * param[in] : contAction : Contains container ID, action type
     * param[out] : status : Response getting after performing container action
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        std::tuple< ContainerManager::DataIn>,
        std::tuple< std::string>,
        std::tuple< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > performContainerActionStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to perform Container App Action
     * param[in] : appAction : Contains container ID, application Name and action type
     * param[out] : status : Response getting after performing container app action
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        std::tuple< ContainerManager::DataIn>,
        std::tuple< std::string>,
        std::tuple< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > performAppActionStubDispatcher;
    
    /*
     * description: 
     * brief : Interface to perform Container Update
     * param[in] : containerPackage : JSON object containing the details of container to be updated
     * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v1::commonapi::toscore::cmservice::ContainerManagerStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>,
        std::tuple< CommonAPI::SomeIP::StringDeployment>
    > performContainerUpdateStubDispatcher;
    
    ContainerManagerSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        ContainerManagerSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< ContainerManagerStub>(_stub)),
        getContainerManagerInterfaceVersionStubDispatcher(&ContainerManagerStub::lockInterfaceVersionAttribute, &ContainerManagerStub::getInterfaceVersion, false, true),
        getVersionStubDispatcher(
            &ContainerManagerStub::getVersion,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        getComponentIDStubDispatcher(
            &ContainerManagerStub::getComponentID,
            false,
            _stub->hasElement(1),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<int32_t>* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::IntegerDeployment<uint8_t>* >(nullptr)))
        
        ,
        getContainerVersionStubDispatcher(
            &ContainerManagerStub::getContainerVersion,
            false,
            _stub->hasElement(2),
            std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        performContainerActionStubDispatcher(
            &ContainerManagerStub::performContainerAction,
            false,
            _stub->hasElement(3),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        performAppActionStubDispatcher(
            &ContainerManagerStub::performAppAction,
            false,
            _stub->hasElement(4),
            std::make_tuple(static_cast< ::v1::commonapi::toscore::cmservice::ContainerManager_::DataInDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
        ,
        performContainerUpdateStubDispatcher(
            &ContainerManagerStub::performContainerUpdate,
            false,
            _stub->hasElement(5),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)),
            std::make_tuple(static_cast< CommonAPI::SomeIP::StringDeployment* >(nullptr)))
        
    {
        /*
         * description: 
         * brief : Interface to get the component version
         * param[in] : request : Dummy integer value
         * param[out] : compVersion : Version of the component
         */
        ContainerManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2711) }, &getVersionStubDispatcher );
        /*
         * description: 
         * brief : Interface to get the component identification number
         * param[in] : request : Dummy integer value
         * param[out] : ComponentID : Component identification number
         */
        ContainerManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2712) }, &getComponentIDStubDispatcher );
        /*
         * description: 
         * brief : Interface to get the version of container
         * param[in] : request : Dummy boolean value
         * param[out] : containerVersionReport : JSON object with container version information
         */
        ContainerManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2713) }, &getContainerVersionStubDispatcher );
        /*
         * description: 
         * brief : Interface to perform Container Action
         * param[in] : contAction : Contains container ID, action type
         * param[out] : status : Response getting after performing container action
         */
        ContainerManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2714) }, &performContainerActionStubDispatcher );
        /*
         * description: 
         * brief : Interface to perform Container App Action
         * param[in] : appAction : Contains container ID, application Name and action type
         * param[out] : status : Response getting after performing container app action
         */
        ContainerManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2715) }, &performAppActionStubDispatcher );
        /*
         * description: 
         * brief : Interface to perform Container Update
         * param[in] : containerPackage : JSON object containing the details of container to be updated
         * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
         */
        ContainerManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2716) }, &performContainerUpdateStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void ContainerManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void ContainerManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v1::commonapi::toscore::cmservice::ContainerManagerStub, typename... _Stubs>
class ContainerManagerSomeIPStubAdapter
    : public ContainerManagerSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    ContainerManagerSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          ContainerManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

#endif // V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_SOMEIP_STUB_ADAPTER_HPP_
