/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSERVICE_CONTAINER_MANAGER_HPP_
#define V1_COMMONAPI_TOSCORE_CMSERVICE_CONTAINER_MANAGER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

class ContainerManager {
public:
    virtual ~ContainerManager() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    /*
     * description: 
     * brief : Structure contains the actions to be performed on the component
     */
    struct DataIn : CommonAPI::Struct< std::string, std::string, std::string, std::string> {
    
        DataIn()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = "";
            std::get< 2>(values_) = "";
            std::get< 3>(values_) = "";
        }
        DataIn(const std::string &_action, const std::string &_containerID, const std::string &_command, const std::string &_appName)
        {
            std::get< 0>(values_) = _action;
            std::get< 1>(values_) = _containerID;
            std::get< 2>(values_) = _command;
            std::get< 3>(values_) = _appName;
        }
        inline const std::string &getAction() const { return std::get< 0>(values_); }
        inline void setAction(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const std::string &getContainerID() const { return std::get< 1>(values_); }
        inline void setContainerID(const std::string &_value) { std::get< 1>(values_) = _value; }
        inline const std::string &getCommand() const { return std::get< 2>(values_); }
        inline void setCommand(const std::string &_value) { std::get< 2>(values_) = _value; }
        inline const std::string &getAppName() const { return std::get< 3>(values_); }
        inline void setAppName(const std::string &_value) { std::get< 3>(values_) = _value; }
        inline bool operator==(const DataIn& _other) const {
        return (getAction() == _other.getAction() && getContainerID() == _other.getContainerID() && getCommand() == _other.getCommand() && getAppName() == _other.getAppName());
        }
        inline bool operator!=(const DataIn &_other) const {
            return !((*this) == _other);
        }
    
    };
};

const char* ContainerManager::getInterface() {
    return ("commonapi.toscore.cmservice.ContainerManager:v1_0");
}

CommonAPI::Version ContainerManager::getInterfaceVersion() {
    return CommonAPI::Version(1, 0);
}

/*
 * description: 
 * brief : Structure contains the actions to be performed on the component
 */

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1

namespace CommonAPI {
}


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSERVICE_CONTAINER_MANAGER_HPP_
