/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_STUB_HPP_
#define V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_STUB_HPP_

#include <functional>
#include <sstream>




#include <v1/commonapi/toscore/cmservice/ContainerManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <string>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service ContainerManager. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class ContainerManagerStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual ContainerManager {
 public:


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for ContainerManager.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ContainerManagerStubRemoteEvent
{
public:
    virtual ~ContainerManagerStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service ContainerManager to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class ContainerManagerStub
    : public virtual CommonAPI::Stub<ContainerManagerStubAdapter, ContainerManagerStubRemoteEvent>
{
public:
    typedef std::function<void (std::string _compVersion)> getVersionReply_t;
    typedef std::function<void (uint8_t _componentID)> getComponentIDReply_t;
    typedef std::function<void (std::string _containerVersionReport)> getContainerVersionReply_t;
    typedef std::function<void (std::string _status)> performContainerActionReply_t;
    typedef std::function<void (std::string _status)> performAppActionReply_t;
    typedef std::function<void (std::string _containerUpdateStatusReport)> performContainerUpdateReply_t;

    virtual ~ContainerManagerStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 6);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    /// This is the method that will be called on remote calls on the method getVersion.
    virtual void getVersion(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getVersionReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : ComponentID : Component identification number
     */
    /// This is the method that will be called on remote calls on the method getComponentID.
    virtual void getComponentID(const std::shared_ptr<CommonAPI::ClientId> _client, int32_t _request, getComponentIDReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to get the version of container
     * param[in] : request : Dummy boolean value
     * param[out] : containerVersionReport : JSON object with container version information
     */
    /// This is the method that will be called on remote calls on the method getContainerVersion.
    virtual void getContainerVersion(const std::shared_ptr<CommonAPI::ClientId> _client, bool _request, getContainerVersionReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to perform Container Action
     * param[in] : contAction : Contains container ID, action type
     * param[out] : status : Response getting after performing container action
     */
    /// This is the method that will be called on remote calls on the method performContainerAction.
    virtual void performContainerAction(const std::shared_ptr<CommonAPI::ClientId> _client, ContainerManager::DataIn _contAction, performContainerActionReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to perform Container App Action
     * param[in] : appAction : Contains container ID, application Name and action type
     * param[out] : status : Response getting after performing container app action
     */
    /// This is the method that will be called on remote calls on the method performAppAction.
    virtual void performAppAction(const std::shared_ptr<CommonAPI::ClientId> _client, ContainerManager::DataIn _appAction, performAppActionReply_t _reply) = 0;
    /*
     * description: 
     * brief : Interface to perform Container Update
     * param[in] : containerPackage : JSON object containing the details of container to be updated
     * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
     */
    /// This is the method that will be called on remote calls on the method performContainerUpdate.
    virtual void performContainerUpdate(const std::shared_ptr<CommonAPI::ClientId> _client, std::string _containerPackage, performContainerUpdateReply_t _reply) = 0;


    using CommonAPI::Stub<ContainerManagerStubAdapter, ContainerManagerStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<ContainerManagerStubAdapter, ContainerManagerStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<ContainerManagerStubAdapter, ContainerManagerStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef ContainerManagerStubRemoteEvent RemoteEventType;
    typedef ContainerManager StubInterface;
};

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_STUB_HPP_
