/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_PROXY_BASE_HPP_
#define V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_PROXY_BASE_HPP_

#include <v1/commonapi/toscore/cmservice/ContainerManager.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <string>
#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

class ContainerManagerProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> GetVersionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const uint8_t&)> GetComponentIDAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> GetContainerVersionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> PerformContainerActionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> PerformAppActionAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::string&)> PerformContainerUpdateAsyncCallback;

    /*
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     */
    virtual void getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : ComponentID : Component identification number
     */
    virtual void getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to get the version of container
     * param[in] : request : Dummy boolean value
     * param[out] : containerVersionReport : JSON object with container version information
     */
    virtual void getContainerVersion(bool _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerVersionReport, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getContainerVersionAsync(const bool &_request, GetContainerVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to perform Container Action
     * param[in] : contAction : Contains container ID, action type
     * param[out] : status : Response getting after performing container action
     */
    virtual void performContainerAction(ContainerManager::DataIn _contAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> performContainerActionAsync(const ContainerManager::DataIn &_contAction, PerformContainerActionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to perform Container App Action
     * param[in] : appAction : Contains container ID, application Name and action type
     * param[out] : status : Response getting after performing container app action
     */
    virtual void performAppAction(ContainerManager::DataIn _appAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> performAppActionAsync(const ContainerManager::DataIn &_appAction, PerformAppActionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;
    /*
     * description: 
     * brief : Interface to perform Container Update
     * param[in] : containerPackage : JSON object containing the details of container to be updated
     * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
     */
    virtual void performContainerUpdate(std::string _containerPackage, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerUpdateStatusReport, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> performContainerUpdateAsync(const std::string &_containerPackage, PerformContainerUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1


// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_PROXY_BASE_HPP_
