/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : Container Manager Interface
 * brief : This API provides API to start/stop/kill containers and containerized Applications. It also provide APIs for full/patch update
 */
#ifndef V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_PROXY_HPP_
#define V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_PROXY_HPP_

#include <v1/commonapi/toscore/cmservice/ContainerManagerProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v1 {
namespace commonapi {
namespace toscore {
namespace cmservice {

template <typename ... _AttributeExtensions>
class ContainerManagerProxy
    : virtual public ContainerManager,
      virtual public ContainerManagerProxyBase,
      virtual public _AttributeExtensions... {
public:
    ContainerManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~ContainerManagerProxy();

    typedef ContainerManager InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * brief : Interface to get the component version
     * param[in] : request : Dummy integer value
     * param[out] : compVersion : Version of the component
     * Calls getVersion with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getVersion with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to get the component identification number
     * param[in] : request : Dummy integer value
     * param[out] : ComponentID : Component identification number
     * Calls getComponentID with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getComponentID with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to get the version of container
     * param[in] : request : Dummy boolean value
     * param[out] : containerVersionReport : JSON object with container version information
     * Calls getContainerVersion with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getContainerVersion(bool _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerVersionReport, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getContainerVersion with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getContainerVersionAsync(const bool &_request, GetContainerVersionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to perform Container Action
     * param[in] : contAction : Contains container ID, action type
     * param[out] : status : Response getting after performing container action
     * Calls performContainerAction with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void performContainerAction(ContainerManager::DataIn _contAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls performContainerAction with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> performContainerActionAsync(const ContainerManager::DataIn &_contAction, PerformContainerActionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to perform Container App Action
     * param[in] : appAction : Contains container ID, application Name and action type
     * param[out] : status : Response getting after performing container app action
     * Calls performAppAction with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void performAppAction(ContainerManager::DataIn _appAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls performAppAction with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> performAppActionAsync(const ContainerManager::DataIn &_appAction, PerformAppActionAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * description: 
     * brief : Interface to perform Container Update
     * param[in] : containerPackage : JSON object containing the details of container to be updated
     * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
     * Calls performContainerUpdate with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void performContainerUpdate(std::string _containerPackage, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerUpdateStatusReport, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls performContainerUpdate with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> performContainerUpdateAsync(const std::string &_containerPackage, PerformContainerUpdateAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< ContainerManagerProxyBase> delegate_;
};

typedef ContainerManagerProxy<> ContainerManagerProxyDefault;


//
// ContainerManagerProxy Implementation
//
template <typename ... _AttributeExtensions>
ContainerManagerProxy<_AttributeExtensions...>::ContainerManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< ContainerManagerProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< ContainerManagerProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
ContainerManagerProxy<_AttributeExtensions...>::~ContainerManagerProxy() {
}

/*
 * description: 
 * brief : Interface to get the component version
 * param[in] : request : Dummy integer value
 * param[out] : compVersion : Version of the component
 */
template <typename ... _AttributeExtensions>
void ContainerManagerProxy<_AttributeExtensions...>::getVersion(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_compVersion, const CommonAPI::CallInfo *_info) {
    delegate_->getVersion(_request, _internalCallStatus, _compVersion, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ContainerManagerProxy<_AttributeExtensions...>::getVersionAsync(const int32_t &_request, GetVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getVersionAsync(_request, _callback, _info);
}
/*
 * description: 
 * brief : Interface to get the component identification number
 * param[in] : request : Dummy integer value
 * param[out] : ComponentID : Component identification number
 */
template <typename ... _AttributeExtensions>
void ContainerManagerProxy<_AttributeExtensions...>::getComponentID(int32_t _request, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_componentID, const CommonAPI::CallInfo *_info) {
    delegate_->getComponentID(_request, _internalCallStatus, _componentID, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ContainerManagerProxy<_AttributeExtensions...>::getComponentIDAsync(const int32_t &_request, GetComponentIDAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getComponentIDAsync(_request, _callback, _info);
}
/*
 * description: 
 * brief : Interface to get the version of container
 * param[in] : request : Dummy boolean value
 * param[out] : containerVersionReport : JSON object with container version information
 */
template <typename ... _AttributeExtensions>
void ContainerManagerProxy<_AttributeExtensions...>::getContainerVersion(bool _request, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerVersionReport, const CommonAPI::CallInfo *_info) {
    delegate_->getContainerVersion(_request, _internalCallStatus, _containerVersionReport, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ContainerManagerProxy<_AttributeExtensions...>::getContainerVersionAsync(const bool &_request, GetContainerVersionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->getContainerVersionAsync(_request, _callback, _info);
}
/*
 * description: 
 * brief : Interface to perform Container Action
 * param[in] : contAction : Contains container ID, action type
 * param[out] : status : Response getting after performing container action
 */
template <typename ... _AttributeExtensions>
void ContainerManagerProxy<_AttributeExtensions...>::performContainerAction(ContainerManager::DataIn _contAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info) {
    delegate_->performContainerAction(_contAction, _internalCallStatus, _status, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ContainerManagerProxy<_AttributeExtensions...>::performContainerActionAsync(const ContainerManager::DataIn &_contAction, PerformContainerActionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->performContainerActionAsync(_contAction, _callback, _info);
}
/*
 * description: 
 * brief : Interface to perform Container App Action
 * param[in] : appAction : Contains container ID, application Name and action type
 * param[out] : status : Response getting after performing container app action
 */
template <typename ... _AttributeExtensions>
void ContainerManagerProxy<_AttributeExtensions...>::performAppAction(ContainerManager::DataIn _appAction, CommonAPI::CallStatus &_internalCallStatus, std::string &_status, const CommonAPI::CallInfo *_info) {
    delegate_->performAppAction(_appAction, _internalCallStatus, _status, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ContainerManagerProxy<_AttributeExtensions...>::performAppActionAsync(const ContainerManager::DataIn &_appAction, PerformAppActionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->performAppActionAsync(_appAction, _callback, _info);
}
/*
 * description: 
 * brief : Interface to perform Container Update
 * param[in] : containerPackage : JSON object containing the details of container to be updated
 * param[out] : containerUpdateStatusReport : JSON object containing the response after performing container update action
 */
template <typename ... _AttributeExtensions>
void ContainerManagerProxy<_AttributeExtensions...>::performContainerUpdate(std::string _containerPackage, CommonAPI::CallStatus &_internalCallStatus, std::string &_containerUpdateStatusReport, const CommonAPI::CallInfo *_info) {
    delegate_->performContainerUpdate(_containerPackage, _internalCallStatus, _containerUpdateStatusReport, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> ContainerManagerProxy<_AttributeExtensions...>::performContainerUpdateAsync(const std::string &_containerPackage, PerformContainerUpdateAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    return delegate_->performContainerUpdateAsync(_containerPackage, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &ContainerManagerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool ContainerManagerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool ContainerManagerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& ContainerManagerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& ContainerManagerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> ContainerManagerProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace cmservice
} // namespace toscore
} // namespace commonapi
} // namespace v1



// Compatibility
namespace v1_0 = v1;

#endif // V1_COMMONAPI_TOSCORE_CMSERVICE_Container_Manager_PROXY_HPP_
