/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#ifndef V0_COMMONAPI_TOSCORE_SMSERVICE_SYSTEM_MANAGER_SOMEIP_STUB_ADAPTER_HPP_
#define V0_COMMONAPI_TOSCORE_SMSERVICE_SYSTEM_MANAGER_SOMEIP_STUB_ADAPTER_HPP_

#include <v0/commonapi/toscore/smservice/SystemManagerStub.hpp>
#include <v0/commonapi/toscore/smservice/SystemManagerSomeIPDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>
#include <CommonAPI/SomeIP/StubAdapterHelper.hpp>
#include <CommonAPI/SomeIP/StubAdapter.hpp>
#include <CommonAPI/SomeIP/Factory.hpp>
#include <CommonAPI/SomeIP/Types.hpp>
#include <CommonAPI/SomeIP/Constants.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

template <typename _Stub = ::v0::commonapi::toscore::smservice::SystemManagerStub, typename... _Stubs>
class SystemManagerSomeIPStubAdapterInternal
    : public virtual SystemManagerStubAdapter,
      public CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...>,
      public std::enable_shared_from_this< SystemManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>>
{
public:
    typedef CommonAPI::SomeIP::StubAdapterHelper< _Stub, _Stubs...> SystemManagerSomeIPStubAdapterHelper;

    ~SystemManagerSomeIPStubAdapterInternal() {
        deactivateManagedInstances();
        SystemManagerSomeIPStubAdapterHelper::deinit();
    }

    void deactivateManagedInstances() {}
    
    CommonAPI::SomeIP::GetAttributeStubDispatcher<
        ::v0::commonapi::toscore::smservice::SystemManagerStub,
        CommonAPI::Version
    > getSystemManagerInterfaceVersionStubDispatcher;

    /*
     * description: 
     * brief : Interface to get version of various TCU packages.
     * param[in]  : reqType : Type of version request.
     * param[out] : response : Structure containing the version and read status.
     */
    CommonAPI::SomeIP::MethodWithReplyStubDispatcher<
        ::v0::commonapi::toscore::smservice::SystemManagerStub,
        std::tuple< SystemManager::VersionReqType>,
        std::tuple< SystemManager::VersionResponse>,
        std::tuple< ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t>,
        std::tuple< ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t>
    > getTCUVersionInfoStubDispatcher;
    
    SystemManagerSomeIPStubAdapterInternal(
        const CommonAPI::SomeIP::Address &_address,
        const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
        const std::shared_ptr<CommonAPI::StubBase> &_stub):
        CommonAPI::SomeIP::StubAdapter(_address, _connection),
        SystemManagerSomeIPStubAdapterHelper(
            _address,
            _connection,
            std::dynamic_pointer_cast< SystemManagerStub>(_stub)),
        getSystemManagerInterfaceVersionStubDispatcher(&SystemManagerStub::lockInterfaceVersionAttribute, &SystemManagerStub::getInterfaceVersion, false, true),
        getTCUVersionInfoStubDispatcher(
            &SystemManagerStub::getTCUVersionInfo,
            false,
            _stub->hasElement(0),
            std::make_tuple(static_cast< ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t* >(nullptr)),
            std::make_tuple(static_cast< ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t* >(nullptr)))
        
    {
        /*
         * description: 
         * brief : Interface to get version of various TCU packages.
         * param[in]  : reqType : Type of version request.
         * param[out] : response : Structure containing the version and read status.
         */
        SystemManagerSomeIPStubAdapterHelper::addStubDispatcher( { CommonAPI::SomeIP::method_id_t(0x2711) }, &getTCUVersionInfoStubDispatcher );
        // Provided events/fields
    }

    // Register/Unregister event handlers for selective broadcasts
    void registerSelectiveEventHandlers();
    void unregisterSelectiveEventHandlers();

};


template <typename _Stub, typename... _Stubs>
void SystemManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::registerSelectiveEventHandlers() {
}

template <typename _Stub, typename... _Stubs>
void SystemManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>::unregisterSelectiveEventHandlers() {
}

template <typename _Stub = ::v0::commonapi::toscore::smservice::SystemManagerStub, typename... _Stubs>
class SystemManagerSomeIPStubAdapter
    : public SystemManagerSomeIPStubAdapterInternal<_Stub, _Stubs...> {
public:
    SystemManagerSomeIPStubAdapter(const CommonAPI::SomeIP::Address &_address,
                                            const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                                            const std::shared_ptr<CommonAPI::StubBase> &_stub)
        : CommonAPI::SomeIP::StubAdapter(_address, _connection),
          SystemManagerSomeIPStubAdapterInternal<_Stub, _Stubs...>(_address, _connection, _stub) {
    }
};

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0

#endif // V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_SOMEIP_STUB_ADAPTER_HPP_
