/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#ifndef V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_STUB_DEFAULT_HPP_
#define V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_STUB_DEFAULT_HPP_


#include <CommonAPI/Export.hpp>

#include <v0/commonapi/toscore/smservice/SystemManagerStub.hpp>
#include <cassert>
#include <sstream>

# if defined(_MSC_VER)
#  if _MSC_VER >= 1300
/*
 * Diamond inheritance is used for the CommonAPI::Proxy base class.
 * The Microsoft compiler put warning (C4250) using a desired c++ feature: "Delegating to a sister class"
 * A powerful technique that arises from using virtual inheritance is to delegate a method from a class in another class
 * by using a common abstract base class. This is also called cross delegation.
 */
#    pragma warning( disable : 4250 )
#  endif
# endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

/**
 * Provides a default implementation for SystemManagerStubRemoteEvent and
 * SystemManagerStub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class COMMONAPI_EXPORT_CLASS_EXPLICIT SystemManagerStubDefault
    : public virtual SystemManagerStub {
public:
    COMMONAPI_EXPORT SystemManagerStubDefault()
        : remoteEventHandler_(this),
          interfaceVersion_(SystemManager::getInterfaceVersion()) {
    }

    COMMONAPI_EXPORT const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) {
        (void)_client;
        return interfaceVersion_;
    }

    COMMONAPI_EXPORT SystemManagerStubRemoteEvent* initStubAdapter(const std::shared_ptr< SystemManagerStubAdapter> &_adapter) {
        CommonAPI::Stub<SystemManagerStubAdapter, SystemManagerStubRemoteEvent>::stubAdapter_ = _adapter;
        return &remoteEventHandler_;
    }

    /*
     * description: 
     * brief : Interface to get version of various TCU packages.
     * param[in]  : reqType : Type of version request.
     * param[out] : response : Structure containing the version and read status.
     */
    COMMONAPI_EXPORT virtual void getTCUVersionInfo(const std::shared_ptr<CommonAPI::ClientId> _client, SystemManager::VersionReqType _reqType, getTCUVersionInfoReply_t _reply) {
        (void)_client;
        (void)_reqType;
        SystemManager::VersionResponse response = {};
        _reply(response);
    }


protected:
    class COMMONAPI_EXPORT_CLASS_EXPLICIT RemoteEventHandler: public virtual SystemManagerStubRemoteEvent {
    public:
        COMMONAPI_EXPORT RemoteEventHandler(SystemManagerStubDefault *_defaultStub)
            : 
              defaultStub_(_defaultStub) {
        }


    private:
        SystemManagerStubDefault *defaultStub_;
    };
protected:
    SystemManagerStubDefault::RemoteEventHandler remoteEventHandler_;

private:


    CommonAPI::Version interfaceVersion_;
};

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_STUB_DEFAULT
