/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#ifndef V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_PROXY_BASE_HPP_
#define V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_PROXY_BASE_HPP_

#include <v0/commonapi/toscore/smservice/SystemManager.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

class SystemManagerProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&, const SystemManager::VersionResponse&)> GetTCUVersionInfoAsyncCallback;

    /*
     * description: 
     * brief : Interface to get version of various TCU packages.
     * param[in]  : reqType : Type of version request.
     * param[out] : response : Structure containing the version and read status.
     */
    virtual void getTCUVersionInfo(SystemManager::VersionReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, SystemManager::VersionResponse &_response, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getTCUVersionInfoAsync(const SystemManager::VersionReqType &_reqType, GetTCUVersionInfoAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr) = 0;

    virtual std::future<void> getCompletionFuture() = 0;
};

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_PROXY_BASE_HPP_
