/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#ifndef V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_STUB_HPP_
#define V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_STUB_HPP_

#include <functional>
#include <sstream>




#include <v0/commonapi/toscore/smservice/SystemManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <string>
#include <vector>


#include <CommonAPI/Stub.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

/**
 * Receives messages from remote and handles all dispatching of deserialized calls
 * to a stub for the service SystemManager. Also provides means to send broadcasts
 * and attribute-changed-notifications of observable attributes as defined by this service.
 * An application developer should not need to bother with this class.
 */
class SystemManagerStubAdapter
    : public virtual CommonAPI::StubAdapter,
      public virtual SystemManager {
 public:


    virtual void deactivateManagedInstances() = 0;


protected:
    /**
     * Defines properties for storing the ClientIds of clients / proxies that have
     * subscribed to the selective broadcasts
     */

};

/**
 * Defines the necessary callbacks to handle remote set events related to the attributes
 * defined in the IDL description for SystemManager.
 * For each attribute two callbacks are defined:
 * - a verification callback that allows to verify the requested value and to prevent setting
 *   e.g. an invalid value ("onRemoteSet<AttributeName>").
 * - an action callback to do local work after the attribute value has been changed
 *   ("onRemote<AttributeName>Changed").
 *
 * This class and the one below are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SystemManagerStubRemoteEvent
{
public:
    virtual ~SystemManagerStubRemoteEvent() { }

};

/**
 * Defines the interface that must be implemented by any class that should provide
 * the service SystemManager to remote clients.
 * This class and the one above are the ones an application developer needs to have
 * a look at if he wants to implement a service.
 */
class SystemManagerStub
    : public virtual CommonAPI::Stub<SystemManagerStubAdapter, SystemManagerStubRemoteEvent>
{
public:
    typedef std::function<void (SystemManager::VersionResponse _response)> getTCUVersionInfoReply_t;

    virtual ~SystemManagerStub() {}
    void lockInterfaceVersionAttribute(bool _lockAccess) { static_cast<void>(_lockAccess); }
    bool hasElement(const uint32_t _id) const {
        return (_id < 1);
    }
    virtual const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client) = 0;

    /*
     * description: 
     * brief : Interface to get version of various TCU packages.
     * param[in]  : reqType : Type of version request.
     * param[out] : response : Structure containing the version and read status.
     */
    /// This is the method that will be called on remote calls on the method getTCUVersionInfo.
    virtual void getTCUVersionInfo(const std::shared_ptr<CommonAPI::ClientId> _client, SystemManager::VersionReqType _reqType, getTCUVersionInfoReply_t _reply) = 0;


    using CommonAPI::Stub<SystemManagerStubAdapter, SystemManagerStubRemoteEvent>::initStubAdapter;
    typedef CommonAPI::Stub<SystemManagerStubAdapter, SystemManagerStubRemoteEvent>::StubAdapterType StubAdapterType;
    typedef CommonAPI::Stub<SystemManagerStubAdapter, SystemManagerStubRemoteEvent>::RemoteEventHandlerType RemoteEventHandlerType;
    typedef SystemManagerStubRemoteEvent RemoteEventType;
    typedef SystemManager StubInterface;
};

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_STUB_HPP_
