/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#ifndef V0_COMMONAPI_TOSCORE_SMSERVICE_SYSTEM_MANAGER_HPP_
#define V0_COMMONAPI_TOSCORE_SMSERVICE_SYSTEM_MANAGER_HPP_




#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <CommonAPI/Types.hpp>
#include <cstdint>
#include <string>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

class SystemManager {
public:
    virtual ~SystemManager() { }

    static inline const char* getInterface();
    static inline CommonAPI::Version getInterfaceVersion();
    
    struct VersionReadStatus : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            ERR_VER_READ_SUCCESS = 0,
            ERR_VER_READ_FAILED = 1,
            ERR_VER_FILE_NOT_FOUND = 2,
            ERR_VER_FILE_OPEN_FAILED = 3,
            ERR_VER_FILE_CORRUPTED = 4
        };
    
        VersionReadStatus()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::ERR_VER_READ_SUCCESS)) {}
        VersionReadStatus(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::ERR_VER_READ_SUCCESS):
                case static_cast< uint8_t>(Literal::ERR_VER_READ_FAILED):
                case static_cast< uint8_t>(Literal::ERR_VER_FILE_NOT_FOUND):
                case static_cast< uint8_t>(Literal::ERR_VER_FILE_OPEN_FAILED):
                case static_cast< uint8_t>(Literal::ERR_VER_FILE_CORRUPTED):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const VersionReadStatus &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const VersionReadStatus &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const VersionReadStatus &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const VersionReadStatus &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const VersionReadStatus &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const VersionReadStatus &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::ERR_VER_READ_SUCCESS): return "ERR_VER_READ_SUCCESS";
            case static_cast< uint8_t>(Literal::ERR_VER_READ_FAILED): return "ERR_VER_READ_FAILED";
            case static_cast< uint8_t>(Literal::ERR_VER_FILE_NOT_FOUND): return "ERR_VER_FILE_NOT_FOUND";
            case static_cast< uint8_t>(Literal::ERR_VER_FILE_OPEN_FAILED): return "ERR_VER_FILE_OPEN_FAILED";
            case static_cast< uint8_t>(Literal::ERR_VER_FILE_CORRUPTED): return "ERR_VER_FILE_CORRUPTED";
            default: return "UNDEFINED";
            }
        }
    };
    /*
     * description: 
     * brief : Structure to hold output parameters for getTCUVersionInfo method
     */
    struct VersionResponse : CommonAPI::Struct< std::string, VersionReadStatus> {
    
        VersionResponse()
        {
            std::get< 0>(values_) = "";
            std::get< 1>(values_) = VersionReadStatus();
        }
        VersionResponse(const std::string &_versionInfo, const VersionReadStatus &_status)
        {
            std::get< 0>(values_) = _versionInfo;
            std::get< 1>(values_) = _status;
        }
        inline const std::string &getVersionInfo() const { return std::get< 0>(values_); }
        inline void setVersionInfo(const std::string &_value) { std::get< 0>(values_) = _value; }
        inline const VersionReadStatus &getStatus() const { return std::get< 1>(values_); }
        inline void setStatus(const VersionReadStatus &_value) { std::get< 1>(values_) = _value; }
        inline bool operator==(const VersionResponse& _other) const {
        return (getVersionInfo() == _other.getVersionInfo() && getStatus() == _other.getStatus());
        }
        inline bool operator!=(const VersionResponse &_other) const {
            return !((*this) == _other);
        }
    
    };
    
    struct VersionReqType : CommonAPI::Enumeration< uint8_t> {
        enum Literal : uint8_t {
            TOS_VERSION = 0,
            QUECTEL_VERSION = 1,
            HARMAN_VERSION = 2,
            IOC_VERSION = 3,
            TOS_CORE_VERSION = 4,
            ESYNC_VERSION = 5,
            ALL_VERSION = 6,
            RESERVED_FOR_FUTURE_1 = 7,
            RESERVED_FOR_FUTURE_2 = 8,
            RESERVED_FOR_FUTURE_3 = 9
        };
    
        VersionReqType()
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(Literal::TOS_VERSION)) {}
        VersionReqType(Literal _literal)
            : CommonAPI::Enumeration< uint8_t>(static_cast< uint8_t>(_literal)) {}
    
        inline bool validate() const {
            switch (value_) {
                case static_cast< uint8_t>(Literal::TOS_VERSION):
                case static_cast< uint8_t>(Literal::QUECTEL_VERSION):
                case static_cast< uint8_t>(Literal::HARMAN_VERSION):
                case static_cast< uint8_t>(Literal::IOC_VERSION):
                case static_cast< uint8_t>(Literal::TOS_CORE_VERSION):
                case static_cast< uint8_t>(Literal::ESYNC_VERSION):
                case static_cast< uint8_t>(Literal::ALL_VERSION):
                case static_cast< uint8_t>(Literal::RESERVED_FOR_FUTURE_1):
                case static_cast< uint8_t>(Literal::RESERVED_FOR_FUTURE_2):
                case static_cast< uint8_t>(Literal::RESERVED_FOR_FUTURE_3):
                return true;
            default:
                return false;
            }
        }
    
        inline bool operator==(const VersionReqType &_other) const { return (value_ == _other.value_); }
        inline bool operator!=(const VersionReqType &_other) const { return (value_ != _other.value_); }
        inline bool operator<=(const VersionReqType &_other) const { return (value_ <= _other.value_); }
        inline bool operator>=(const VersionReqType &_other) const { return (value_ >= _other.value_); }
        inline bool operator<(const VersionReqType &_other) const { return (value_ < _other.value_); }
        inline bool operator>(const VersionReqType &_other) const { return (value_ > _other.value_); }
    
        inline bool operator==(const Literal &_value) const { return (value_ == static_cast< uint8_t>(_value)); }
        inline bool operator!=(const Literal &_value) const { return (value_ != static_cast< uint8_t>(_value)); }
        inline bool operator<=(const Literal &_value) const { return (value_ <= static_cast< uint8_t>(_value)); }
        inline bool operator>=(const Literal &_value) const { return (value_ >= static_cast< uint8_t>(_value)); }
        inline bool operator<(const Literal &_value) const { return (value_ < static_cast< uint8_t>(_value)); }
        inline bool operator>(const Literal &_value) const { return (value_ > static_cast< uint8_t>(_value)); }
    
        const char* toString() const noexcept
        {
            switch(value_)
            {
            case static_cast< uint8_t>(Literal::TOS_VERSION): return "TOS_VERSION";
            case static_cast< uint8_t>(Literal::QUECTEL_VERSION): return "QUECTEL_VERSION";
            case static_cast< uint8_t>(Literal::HARMAN_VERSION): return "HARMAN_VERSION";
            case static_cast< uint8_t>(Literal::IOC_VERSION): return "IOC_VERSION";
            case static_cast< uint8_t>(Literal::TOS_CORE_VERSION): return "TOS_CORE_VERSION";
            case static_cast< uint8_t>(Literal::ESYNC_VERSION): return "ESYNC_VERSION";
            case static_cast< uint8_t>(Literal::ALL_VERSION): return "ALL_VERSION";
            case static_cast< uint8_t>(Literal::RESERVED_FOR_FUTURE_1): return "RESERVED_FOR_FUTURE_1";
            case static_cast< uint8_t>(Literal::RESERVED_FOR_FUTURE_2): return "RESERVED_FOR_FUTURE_2";
            case static_cast< uint8_t>(Literal::RESERVED_FOR_FUTURE_3): return "RESERVED_FOR_FUTURE_3";
            default: return "UNDEFINED";
            }
        }
    };
};

const char* SystemManager::getInterface() {
    return ("commonapi.toscore.smservice.SystemManager:v0_1");
}

CommonAPI::Version SystemManager::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}

/*
 * description: 
 * brief : Structure to hold output parameters for getTCUVersionInfo method
 */
/*
 * description: 
 * brief : Enumeration indicating the version
 */
/*
 * description: 
 * brief : Enumeration indicating the status of version read operation
 */

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0

namespace CommonAPI {
}


// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_TOSCORE_SMSERVICE_SYSTEM_MANAGER_HPP_
