/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
#include <v0/commonapi/toscore/smservice/SystemManagerSomeIPStubAdapter.hpp>
#include <v0/commonapi/toscore/smservice/SystemManager.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

std::shared_ptr<CommonAPI::SomeIP::StubAdapter> createSystemManagerSomeIPStubAdapter(
                   const CommonAPI::SomeIP::Address &_address,
                   const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection,
                   const std::shared_ptr<CommonAPI::StubBase> &_stub) {
    return std::make_shared< SystemManagerSomeIPStubAdapter<::v0::commonapi::toscore::smservice::SystemManagerStub>>(_address, _connection, _stub);
}

void initializeSystemManagerSomeIPStubAdapter() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.toscore.smservice.SystemManager:v0_1:commonapi.toscore.smservice.SystemManager",
         0xfa9, 0x7d9, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerStubAdapterCreateMethod(
        "commonapi.toscore.smservice.SystemManager:v0_1",
        &createSystemManagerSomeIPStubAdapter);
}

INITIALIZER(registerSystemManagerSomeIPStubAdapter) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSystemManagerSomeIPStubAdapter);
}

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0
