/*
 * This file was generated by the CommonAPI Generators.
 * Used org.genivi.commonapi.someip 3.2.0.v202012010944.
 * Used org.franca.core 0.13.1.201807231814.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at
 * http://mozilla.org/MPL/2.0/.
 */
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#include <v0/commonapi/toscore/smservice/SystemManagerSomeIPProxy.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

#include <CommonAPI/SomeIP/AddressTranslator.hpp>

#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

std::shared_ptr<CommonAPI::SomeIP::Proxy> createSystemManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection) {
    return std::make_shared< SystemManagerSomeIPProxy>(_address, _connection);
}

void initializeSystemManagerSomeIPProxy() {
    CommonAPI::SomeIP::AddressTranslator::get()->insert(
        "local:commonapi.toscore.smservice.SystemManager:v0_1:commonapi.toscore.smservice.SystemManager",
        0xfa9, 0x7d9, 0, 1);
    CommonAPI::SomeIP::Factory::get()->registerProxyCreateMethod(
        "commonapi.toscore.smservice.SystemManager:v0_1",
        &createSystemManagerSomeIPProxy);
}

INITIALIZER(registerSystemManagerSomeIPProxy) {
    CommonAPI::SomeIP::Factory::get()->registerInterface(initializeSystemManagerSomeIPProxy);
}

SystemManagerSomeIPProxy::SystemManagerSomeIPProxy(
    const CommonAPI::SomeIP::Address &_address,
    const std::shared_ptr<CommonAPI::SomeIP::ProxyConnection> &_connection)
        : CommonAPI::SomeIP::Proxy(_address, _connection)
{
}

SystemManagerSomeIPProxy::~SystemManagerSomeIPProxy() {
    completed_.set_value();
}



/*
 * description: 
 * brief : Interface to get version of various TCU packages.
 * param[in]  : reqType : Type of version request.
 * param[out] : response : Structure containing the version and read status.
 */
void SystemManagerSomeIPProxy::getTCUVersionInfo(SystemManager::VersionReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, SystemManager::VersionResponse &_response, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< SystemManager::VersionReqType, ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t> deploy_reqType(_reqType, static_cast< ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< SystemManager::VersionResponse, ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t> deploy_response(static_cast< ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t* >(nullptr));
    CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SystemManager::VersionReqType,
                ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SystemManager::VersionResponse,
                ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t
            >
        >
    >::callMethodWithReply(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2711),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_reqType,
        _internalCallStatus,
        deploy_response);
    _response = deploy_response.getValue();
}

std::future<CommonAPI::CallStatus> SystemManagerSomeIPProxy::getTCUVersionInfoAsync(const SystemManager::VersionReqType &_reqType, GetTCUVersionInfoAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    CommonAPI::Deployable< SystemManager::VersionReqType, ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t> deploy_reqType(_reqType, static_cast< ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t* >(nullptr));
    CommonAPI::Deployable< SystemManager::VersionResponse, ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t> deploy_response(static_cast< ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t* >(nullptr));
    return CommonAPI::SomeIP::ProxyHelper<
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SystemManager::VersionReqType,
                ::v0::commonapi::toscore::smservice::SystemManager_::VersionReqTypeDeployment_t
            >
        >,
        CommonAPI::SomeIP::SerializableArguments<
            CommonAPI::Deployable<
                SystemManager::VersionResponse,
                ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t
            >
        >
    >::callMethodAsync(
        *this,
        CommonAPI::SomeIP::method_id_t(0x2711),
        true,
        false,
        (_info ? _info : &CommonAPI::SomeIP::defaultCallInfo),
        deploy_reqType,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< SystemManager::VersionResponse, ::v0::commonapi::toscore::smservice::SystemManager_::VersionResponseDeployment_t > _response) {
            if (_callback)
                _callback(_internalCallStatus, _response.getValue());
        },
        std::make_tuple(deploy_response));
}

void SystemManagerSomeIPProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
    ownVersionMajor = 0;
    ownVersionMinor = 1;
}

std::future<void> SystemManagerSomeIPProxy::getCompletionFuture() {
    return completed_.get_future();
}

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0
