/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.2.0.v202012010850.
* Used org.franca.core 0.13.1.201807231814.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * title : System Manager Interface
 * brief : This interface provides System Manager Functions
 */
#ifndef V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_PROXY_HPP_
#define V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_PROXY_HPP_

#include <v0/commonapi/toscore/smservice/SystemManagerProxyBase.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#define HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif


#if defined (HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE)
#undef COMMONAPI_INTERNAL_COMPILATION
#undef HAS_DEFINED_COMMONAPI_INTERNAL_COMPILATION_HERE
#endif

namespace v0 {
namespace commonapi {
namespace toscore {
namespace smservice {

template <typename ... _AttributeExtensions>
class SystemManagerProxy
    : virtual public SystemManager,
      virtual public SystemManagerProxyBase,
      virtual public _AttributeExtensions... {
public:
    SystemManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate);
    ~SystemManagerProxy();

    typedef SystemManager InterfaceType;


    /**
     * Returns the CommonAPI address of the remote partner this proxy communicates with.
     */
    virtual const CommonAPI::Address &getAddress() const;

    /**
     * Returns true if the remote partner for this proxy is currently known to be available.
     */
    virtual bool isAvailable() const;

    /**
     * Returns true if the remote partner for this proxy is available.
     */
    virtual bool isAvailableBlocking() const;

    /**
     * Returns the wrapper class that is used to (de-)register for notifications about
     * the availability of the remote partner of this proxy.
     */
    virtual CommonAPI::ProxyStatusEvent& getProxyStatusEvent();

    /**
     * Returns the wrapper class that is used to access version information of the remote
     * partner of this proxy.
     */
    virtual CommonAPI::InterfaceVersionAttribute& getInterfaceVersionAttribute();

    virtual std::future<void> getCompletionFuture();

    /**
     * description: 
     * brief : Interface to get version of various TCU packages.
     * param[in]  : reqType : Type of version request.
     * param[out] : response : Structure containing the version and read status.
     * Calls getTCUVersionInfo with synchronous semantics.
     *
     * All const parameters are input parameters to this method.
     * All non-const parameters will be filled with the returned values.
     * The CallStatus will be filled when the method returns and indicate either
     * "SUCCESS" or which type of error has occurred. In case of an error, ONLY the CallStatus
     * will be set.
     */
    virtual void getTCUVersionInfo(SystemManager::VersionReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, SystemManager::VersionResponse &_response, const CommonAPI::CallInfo *_info = nullptr);
    /**
     * Calls getTCUVersionInfo with asynchronous semantics.
     *
     * The provided callback will be called when the reply to this call arrives or
     * an error occurs during the call. The CallStatus will indicate either "SUCCESS"
     * or which type of error has occurred. In case of any error, ONLY the CallStatus
     * will have a defined value.
     * The std::future returned by this method will be fulfilled at arrival of the reply.
     * It will provide the same value for CallStatus as will be handed to the callback.
     */
    virtual std::future<CommonAPI::CallStatus> getTCUVersionInfoAsync(const SystemManager::VersionReqType &_reqType, GetTCUVersionInfoAsyncCallback _callback = nullptr, const CommonAPI::CallInfo *_info = nullptr);



 private:
    std::shared_ptr< SystemManagerProxyBase> delegate_;
};

typedef SystemManagerProxy<> SystemManagerProxyDefault;


//
// SystemManagerProxy Implementation
//
template <typename ... _AttributeExtensions>
SystemManagerProxy<_AttributeExtensions...>::SystemManagerProxy(std::shared_ptr<CommonAPI::Proxy> delegate):
        _AttributeExtensions(*(std::dynamic_pointer_cast< SystemManagerProxyBase>(delegate)))...,
        delegate_(std::dynamic_pointer_cast< SystemManagerProxyBase>(delegate)) {
}

template <typename ... _AttributeExtensions>
SystemManagerProxy<_AttributeExtensions...>::~SystemManagerProxy() {
}

/*
 * description: 
 * brief : Interface to get version of various TCU packages.
 * param[in]  : reqType : Type of version request.
 * param[out] : response : Structure containing the version and read status.
 */
template <typename ... _AttributeExtensions>
void SystemManagerProxy<_AttributeExtensions...>::getTCUVersionInfo(SystemManager::VersionReqType _reqType, CommonAPI::CallStatus &_internalCallStatus, SystemManager::VersionResponse &_response, const CommonAPI::CallInfo *_info) {
    if (!_reqType.validate()) {
        _internalCallStatus = CommonAPI::CallStatus::INVALID_VALUE;
        return;
    }
    delegate_->getTCUVersionInfo(_reqType, _internalCallStatus, _response, _info);
}

template <typename ... _AttributeExtensions>
std::future<CommonAPI::CallStatus> SystemManagerProxy<_AttributeExtensions...>::getTCUVersionInfoAsync(const SystemManager::VersionReqType &_reqType, GetTCUVersionInfoAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
    if (!_reqType.validate()) {
        SystemManager::VersionResponse response = {};
        _callback(CommonAPI::CallStatus::INVALID_VALUE, response);
        std::promise<CommonAPI::CallStatus> promise;
        promise.set_value(CommonAPI::CallStatus::INVALID_VALUE);
        return promise.get_future();
    }
    return delegate_->getTCUVersionInfoAsync(_reqType, _callback, _info);
}

template <typename ... _AttributeExtensions>
const CommonAPI::Address &SystemManagerProxy<_AttributeExtensions...>::getAddress() const {
    return delegate_->getAddress();
}

template <typename ... _AttributeExtensions>
bool SystemManagerProxy<_AttributeExtensions...>::isAvailable() const {
    return delegate_->isAvailable();
}

template <typename ... _AttributeExtensions>
bool SystemManagerProxy<_AttributeExtensions...>::isAvailableBlocking() const {
    return delegate_->isAvailableBlocking();
}

template <typename ... _AttributeExtensions>
CommonAPI::ProxyStatusEvent& SystemManagerProxy<_AttributeExtensions...>::getProxyStatusEvent() {
    return delegate_->getProxyStatusEvent();
}

template <typename ... _AttributeExtensions>
CommonAPI::InterfaceVersionAttribute& SystemManagerProxy<_AttributeExtensions...>::getInterfaceVersionAttribute() {
    return delegate_->getInterfaceVersionAttribute();
}


template <typename ... _AttributeExtensions>
std::future<void> SystemManagerProxy<_AttributeExtensions...>::getCompletionFuture() {
    return delegate_->getCompletionFuture();
}

} // namespace smservice
} // namespace toscore
} // namespace commonapi
} // namespace v0



// Compatibility
namespace v0_1 = v0;

#endif // V0_COMMONAPI_TOSCORE_SMSERVICE_System_Manager_PROXY_HPP_
